lib/src/render/toolbar/toolbar_item.dart

Due to Material wrapping LinkMenu, the Materials white background can be seen because LinkMenus Container has a BorderRadius which Material does not.
Resolves #18

fix: issue with LinkMenu inside Material

---

lib/src/service/internal_key_event_handlers/arrow_keys_handler.dart
lib/src/service/shortcut_event/built_in_shortcut_events.dart
test/service/internal_key_event_handlers/arrow_keys_handler_test.dart
test/service/shortcut_event/shortcut_event_test.dart

Relates: https://github.com/AppFlowy-IO/AppFlowy/issues/2071

feat: alt + arrow key to move cursor one word

---

test/service/internal_key_event_handlers/redo_undo_handler_test.dart

Related to Issue #16 
Added new tests to cover the following:

test: redo undo with text formatting

---

lib/src/render/image/image_node_builder.dart
lib/src/render/image/image_node_widget.dart
lib/src/render/rich_text/flowy_rich_text.dart
lib/src/service/render_plugin_service.dart
test/infra/test_editor.dart
test/render/image/image_node_builder_test.dart
test/render/image/image_node_widget_test.dart
test/render/link_menu/link_menu_test.dart

There are two changes here:
- Stop showing action menu and edge resize on image node when editor is not editable
- Stop showing link menu on tapping a link if editor is not editable (if you click a link in non-editable mode, you open it.)

fix: cannot edit image or see link menu if editorState is uneditable

---

documentation/customizing.md

#35  Fixed documentation typo  in appflowy-editor/documentation/customisation.md file under customizing a component

fixed documentation typo issue: #35 

---

lib/src/render/toolbar/toolbar_item.dart
lib/src/service/shortcut_event/shortcut_event.dart

fix: avoid using Platform code in Web #44

---

example/lib/home_page.dart
lib/src/render/style/editor_style.dart

fix: lessen horizontal editor padding for mobile

---

lib/src/service/internal_key_event_handlers/enter_without_shift_in_text_node_handler.dart
test/service/internal_key_event_handlers/enter_without_shift_in_text_node_handler_test.dart

Closes: https://github.com/AppFlowy-IO/AppFlowy/issues/2275

fix: enter to outdent checkbox/bullet lists

---

lib/src/service/internal_key_event_handlers/markdown_syntax_to_styled_text.dart
lib/src/service/shortcut_event/built_in_shortcut_events.dart

Closes: https://github.com/AppFlowy-IO/AppFlowy/issues/1059

feat: support single asterisk to italic

---

lib/src/render/style/editor_style.dart
lib/src/service/shortcut_event/shortcut_event.dart

fix: remove platform check in theme on web

---

lib/src/core/document/attributes.dart
lib/src/service/default_text_operations/format_rich_text_style.dart
test/service/default_text_operations/format_rich_text_style_test.dart

Closes https://github.com/AppFlowy-IO/AppFlowy/issues/2171

fix: changing heading from one level to another from toolbar

---

lib/src/render/image/image_node_widget.dart

The image placeholder color now matches Divider's color, so it will be visible both on the light and dark themes

fix: fixed image placeholder border color

---

.github/workflows/commit_lint.yml
.github/workflows/test.yml
example/lib/plugin/AI/continue_to_write.dart
example/lib/plugin/AI/smart_edit.dart
example/pubspec.yaml
lib/src/core/document/deprecated/node.dart
lib/src/core/document/node.dart
lib/src/core/transform/operation.dart
lib/src/editor/block_component/base_component/markdown_format_helper.dart
lib/src/editor/command/text_commands.dart
lib/src/editor/editor_component/service/ime/delta_input_service.dart
lib/src/flutter/overlay.dart
lib/src/history/undo_manager.dart
lib/src/l10n/intl/messages_all.dart
lib/src/render/rich_text/built_in_text_widget.dart
lib/src/render/selection_menu/selection_menu_widget.dart
lib/src/service/input_service.dart
pubspec.yaml
test/extensions/node_extension_test.dart

CC @LucasXu0 
Do you want me to do this on the mobile branch instead of the main branch?

chore: upgrade flutter to 3.10.1

---

lib/src/editor/editor_component/service/renderer/block_component_action.dart

I removed the action container when there is no action(in mobile). The previous code still occupy a space when `showActions` is false

fix: remove action container space in mobile

---

example/assets/example.html
example/assets/example.json
example/lib/home_page.dart
example/pubspec.yaml
lib/appflowy_editor.dart
lib/src/core/document/document.dart
lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart
lib/src/editor/block_component/heading_block_component/heading_block_component.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/quote_block_component/quote_block_component.dart
lib/src/editor/block_component/text_block_component/text_block_component.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/paste_command.dart
lib/src/editor/toolbar/desktop/floating_toolbar.dart
lib/src/editor/util/color_util.dart
lib/src/editor_state.dart
lib/src/infra/html_converter.dart
lib/src/plugins/html/html_document.dart
lib/src/plugins/html/html_document_decoder.dart
lib/src/plugins/html/html_document_encoder.dart
test/infra/html_converter_test.dart
test/service/internal_key_event_handlers/checkbox_event_handler_test.dart
test/service/internal_key_event_handlers/outdent_handler_test.dart
test/service/internal_key_event_handlers/tab_handler_test.dart

fix: Problem with the position of the floating operation bar

---

lib/appflowy_editor.dart
lib/src/plugins/html/html_document_decoder.dart
lib/src/plugins/html/html_document_encoder.dart
test/plugins/html/decoder/document_html_decoder_test.dart
test/plugins/html/encoder/document_html_encoder_test.dart
test/plugins/html/html_document_test.dart

fix:editor document to html encoder added

---

lib/src/editor/block_component/heading_block_component/heading_block_component.dart
lib/src/plugins/html/html_document_decoder.dart
lib/src/plugins/html/html_document_encoder.dart
test/plugins/html/decoder/document_html_decoder_test.dart
test/plugins/html/encoder/document_html_encoder_test.dart
test/plugins/html/html_document_test.dart

fix: nested elements getting ignored

---

lib/appflowy_editor.dart
lib/src/editor/block_component/base_component/outdent_command.dart

Adds an export of the `key_mapping.dart` file from the appflowy_editor.dart barrel file. 
Fixes a typo by changing the key of the outdent handler from `indent` to `outdent`

chore: export keymapping file and fix outdent typo

---

lib/src/editor/block_component/heading_block_component/heading_character_shortcut.dart
test/new/block_component/heading_block_component/heading_character_shortcut_test.dart

fix: tabbing whitespace at the front will convert current paragraph into heading

---

lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_left_command.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_right_command.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/end_command.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/home_command.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/undo_redo_command.dart
test/new/service/shortcuts/command_shortcut_events/end_command_test.dart
test/new/service/shortcuts/command_shortcut_events/home_command_test.dart

The default behavior of the home key on Windows/Linux is to navigate the cursor to the start of a line.
The default behavior of the home key on MacOS is to scroll the page to the top of the document.
Currently, we only support the MacOS behavior, this PR aims to make the cursor navigate to the start of a line on Windows/Linux.
It also introduces a new shortcut `Ctrl+Home` to scroll to the top of the document in Windows and `Ctrl+End` to scroll to the bottom of the document. 
The default behavior for MacOS is retained:
- `Ctrl+arrow keys` to go to the beginning or end of a line.
- `Home` and `End`keys to scroll in the document.
Solves [#2817](https://github.com/AppFlowy-IO/AppFlowy/issues/2817).

fix: behaviour of home and end keys on windows

---

lib/src/plugins/markdown/decoder/delta_markdown_decoder.dart
lib/src/plugins/markdown/decoder/document_markdown_decoder.dart
test/plugins/markdown/decoder/document_markdown_decoder_test.dart

This PR is related to issue https://github.com/AppFlowy-IO/AppFlowy/issues/2781 
Earlier the code block was being treated as a regular paragraph and was being returned as regular paragraph node now it is return as a node of type code.
Before -
After-

Added code block support for conversion from  markdown to document

---

lib/src/editor/toolbar/desktop/floating_toolbar.dart
test/new/infra/testable_editor.dart
test/new/toolbar/desktop/floating_toolbar_test.dart

At most top toolbar position goes out of the screen. Added a condition to check and position it on the bottom of the line.
https://github.com/AppFlowy-IO/appflowy-editor/assets/3286303/bf8b4d44-f897-4731-bd62-9343a1a16917
https://github.com/AppFlowy-IO/appflowy-editor/assets/3286303/8ae6fbec-1f86-4cfa-8c2f-ead14a4ae11b

fix: toolbar position at most top

---

lib/src/editor/editor_component/service/scroll/auto_scrollable_widget.dart
lib/src/editor/editor_component/service/scroll_service_widget.dart
lib/src/editor/editor_component/service/selection/mobile_selection_service.dart

fix: mobile selection scroll should work on both side

---

lib/src/core/document/text_delta.dart
test/core/document/text_delta_test.dart

fix: the cursor is inaccuracy when the text contains special emoji

---

lib/src/editor/block_component/divider_block_component/divider_character_shortcut.dart
lib/src/editor/block_component/quote_block_component/quote_character_shortcut.dart
lib/src/editor/editor_component/service/ime/delta_input_on_delete_impl.dart
lib/src/editor/editor_component/service/ime/delta_input_service.dart

closes #241 
Two `-` will be connected on the mobile.
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/a4b5254f-75da-4c4f-92bd-99be3cdbb17c

fix: error occurs when applying divider on Mobile

---

lib/src/editor/block_component/divider_block_component/divider_character_shortcut.dart
lib/src/editor/block_component/quote_block_component/quote_character_shortcut.dart
lib/src/editor/editor_component/service/ime/delta_input_on_delete_impl.dart
lib/src/editor/editor_component/service/ime/delta_input_service.dart
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/editor_component/service/ime/text_diff.dart
lib/src/editor/editor_component/service/keyboard_service_widget.dart

`DeltaTextInputClient` has different behavior on different platforms, making it hard to maintain the state. Therefore, I'm trying to replace it with `TextInputClient` and implement the diff myself.

feat: replace DeltaTextInputClient with TextInputClient

---

lib/src/plugins/markdown/decoder/custom_syntaxes/underline_syntax.dart
lib/src/plugins/markdown/decoder/delta_markdown_decoder.dart
test/plugins/markdown/decoder/delta_markdown_decoder_test.dart

The underline tag is not detected correctly, this PR introduces a syntax parser for underline tag, additionally keeping open a possibility to add more custom parsers

fix: add underline syntax parser

---

lib/src/editor/toolbar/desktop/items/format_toolbar_items.dart
lib/src/editor/toolbar/desktop/items/heading_toolbar_items.dart

While implementing the editor into my app, I noticed the desktop tooltips were incorrect:
As seen above, H2 and H3 still had the tooltip of H1, and the italics option had the tooltip of "bold". This is also reflected in the official AppFlowy app, but is a very quick and simple fix :D

fix: desktop tooltips incorrect

---

analysis_options.yaml
example/lib/home_page.dart
example/lib/pages/simple_editor.dart
lib/appflowy_editor.dart
lib/src/editor/block_component/block_component.dart
lib/src/editor/block_component/divider_block_component/divider_character_shortcut.dart
lib/src/editor/block_component/divider_block_component/divider_menu_item.dart
lib/src/editor/block_component/image_block_component/image_block_component.dart
lib/src/editor/block_component/image_block_component/image_upload_widget.dart
lib/src/editor/block_component/image_block_component/resizable_image.dart
lib/src/editor/editor_component/service/ime/delta_input_on_delete_impl.dart
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/editor_component/service/shortcuts/character_shortcut_events/slash_command.dart
lib/src/infra/html_converter.dart
lib/src/plugins/html/html_document_decoder.dart
lib/src/render/image/image_upload_widget.dart
lib/src/render/selection_menu/selection_menu_service.dart
test/customer/custom_image_menu_test.dart
test/plugins/html/decoder/document_html_decoder_test.dart
test/plugins/html/encoder/document_html_encoder_test.dart
test/plugins/html/html_document_test.dart
test/render/image/image_node_builder_test.dart

I only implemented this menu in AppFlowy.
Anyone wants to customize the image menu on your own style, please use the below code.
```dart
final customBlockComponentBuilders = {
...standardBlockComponentBuilderMap,
ImageBlockKeys.type: ImageBlockComponentBuilder(
showMenu: true,
menuBuilder: (node, _) {
return const Positioned(
right: 10,
child: Text('Sample Menu'),
);
},
)
};
return AppFlowyEditor.custom(
editorState: editorState,
scrollController: scrollController,
blockComponentBuilders: customBlockComponentBuilders,
commandShortcutEvents: standardCommandShortcutEvents,
characterShortcutEvents: standardCharacterShortcutEvents,
);
```

feat: support customizing image menu

---

lib/src/editor/block_component/base_component/block_icon_builder.dart
lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/quote_block_component/quote_block_component.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
lib/src/editor/toolbar/desktop/items/icon_item_widget.dart
test/customer/custom_block_icon_test.dart
test/customer/custom_image_menu_test.dart

Support customizing the built-in block's icon
Here's the sample code 
```dart
final iconMap = {
BulletedListBlockKeys.type: Icons.format_list_bulleted,
NumberedListBlockKeys.type: Icons.format_list_numbered,
QuoteBlockKeys.type: Icons.format_quote,
TodoListBlockKeys.type: Icons.check_box_outline_blank,
};
class CustomBlockIcon extends StatelessWidget {
const CustomBlockIcon({super.key});
@override
Widget build(BuildContext context) {
final delta = Delta()..insert('Hello World');
final document = Document.blank()
..insert(
[0],
[
bulletedListNode(delta: delta),
numberedListNode(delta: delta),
todoListNode(delta: delta, checked: false),
quoteNode(delta: delta),
],
);
final customBlockComponentBuilders = {
...standardBlockComponentBuilderMap,
BulletedListBlockKeys.type: …
```

feat: support customizing the block icon

---

documentation/customizing.md
lib/src/render/style/editor_style.dart

Linked to https://github.com/AppFlowy-IO/appflowy-editor/issues/258
Updated the documentation to make it more clear that `EditorStyle.dark` has been depreciated :)

docs: updated theming documentation to reflect depreciations

---

example/lib/main.dart
lib/src/editor/editor_component/service/ime/delta_input_impl.dart
lib/src/editor/editor_component/service/ime/delta_input_service.dart
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/editor_component/service/ime/text_input_service.dart
lib/src/editor/editor_component/service/keyboard_service_widget.dart
test/new/infra/testable_editor.dart

Fix #239 
The keyboard appearance will use the same brightness(light or dark) as the current system theme.

fix: keep keyboard appearance as same brightness as system theme

---

example/android/app/src/main/AndroidManifest.xml
example/ios/Runner/Info.plist
example/lib/home_page.dart
example/lib/main.dart

Additionally removes surfaceTintColor from AppBar, as it looks weird when body is behind appbar. Also resolves issue with _editorState not being initialized on reassemble in debugging.
Closes: #71

fix: add support for query schemes in example app

---

lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/undo_redo_command.dart
test/new/service/shortcuts/command_shortcut_events/undo_redo_command_test.dart
test/service/internal_key_event_handlers/redo_undo_handler_test.dart

I have changed the default shortcut for redo operation on Windows and Linux from `ctrl+shift+z` to `ctrl+y`.
Partially Solves: [#2888](https://github.com/AppFlowy-IO/AppFlowy/issues/2888)

chore: change windows and linux command for redo

---

lib/src/editor/toolbar/mobile/toolbar_items/heading_mobile_toolbar_item.dart

To fix #285 
I refactored the UI to make sure it always has three buttons on the heading mobile toolbar menu.
If the width of the screen is too small, the button texts will show in 2 lines

fix: fix overflow in heading mobile toolbar menu

---

lib/src/editor/toolbar/desktop/items/icon_item_widget.dart

linked to https://github.com/AppFlowy-IO/appflowy-editor/issues/302
[Bug] Toolbar Item Tooltips are too responsive
https://github.com/AppFlowy-IO/appflowy-editor/assets/22239637/6f043058-72d9-4dfa-b20e-c3ca35ceed15

fix: toolbar item tooltips are too responsive

---

lib/src/editor/block_component/base_component/convert_to_paragraph_command.dart

For developers who want to customize the backspace command for converting the block type.
```dart
@override
void initState() {
super.initState();
indentableBlockTypes.add(ToggleListBlockKeys.type);
convertibleBlockTypes.add(ToggleListBlockKeys.type);
}
```

chore: support extending the convertibleBlockTypes

---

lib/src/editor/block_component/base_component/text_direction_mixin.dart
lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/text_block_component/text_block_component.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
lib/src/editor/editor_component/service/renderer/block_component_widget.dart
test/new/block_component/text_direction_mixin_test.dart
test/new/service/shortcuts/command_shortcut_events/backspace_command_test.dart
test/new/service/shortcuts/command_shortcut_events/indent_command_test.dart

Also introduced last direction concept.
/cc @LucasXu0 These are changes from what we discussed before in Discord.
I tried to add at least one test for each change that I made, With one exception which I've commented on [here](https://github.com/AppFlowy-IO/appflowy-editor/pull/318/files#diff-1f2951926e897234d6e35b6fd2530be3a8da29b80879ae0dc503d93341d18f5aR103).

fix: indent padding from left when rtl

---

lib/src/plugins/markdown/decoder/document_markdown_decoder.dart
pubspec.yaml
test/plugins/markdown/decoder/document_markdown_decoder_test.dart

This PR adds support to detect images from markdown file which are in ![Alt text](path to image) format
It also fixes the error where if a file is there in markdown file it is detected as a url since both have a similar representation in markdown - [Alt tex](url or file path) not if it is a file it is treated as a simple paragraph  with text "This is currently not supported : [Alt text](file path)"
Related to https://github.com/AppFlowy-IO/AppFlowy/pull/2981

Import assets from markdown file

---

lib/src/plugins/markdown/decoder/document_markdown_decoder.dart
test/plugins/markdown/decoder/document_markdown_decoder_test.dart

Fixes: #334 
Before-
https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/eb0aa0a3-ef92-4a7c-8e97-af13688dd512
After-
https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/26a4bb18-c480-41f7-90af-bec3385bbad3

fix: fixed numbered list being treated as a paragraph

---

lib/src/editor/selection_menu/selection_menu_widget.dart

Sometimes we need `BuildContext` to build a new node. 
For example in the callout feature, if we want to insert a new callout node with a background color that matches the current theme, we need `BuildContext` to get its color to build the node.

feat: expose context in nodeBuilder

---

lib/src/plugins/markdown/encoder/parser/code_block_node_parser.dart
test/plugins/markdown/encoder/parser/text_node_parser_test.dart

fixes: https://github.com/AppFlowy-IO/AppFlowy/issues/3055
Before -
https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/c760decc-0561-4dec-bb30-ee97795d6b52
After -
https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/3c2e2287-7cbc-475d-9edf-1e43a1f298e0

fix: fixed the issue of code block not being exported in markdown

---

lib/src/service/context_menu/built_in_context_menu_item.dart
test/service/context_menu_test.dart

fixes: https://github.com/AppFlowy-IO/AppFlowy/issues/3077
Before-
https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/17d2e72e-98a3-4162-b77e-1558df756156
After-
https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/9f899a05-253f-4ea8-8f68-930752a241a1

fix: fixed unresponsive behaviour of context menu items

---

lib/src/editor/block_component/image_block_component/image_upload_widget.dart
lib/src/editor/selection_menu/selection_menu_service.dart
lib/src/editor/toolbar/desktop/floating_toolbar.dart

When the selection rect is in the right half of editor show selection menu on left.
closes #329

fix: show selection menu at left

---

lib/src/service/default_text_operations/format_rich_text_style.dart
test/service/format_rich_text_style_test.dart

modified insertNodeAfterSelection to copy current node text direction to the node which is going to get inserteded.
resolves #331

fix: selection menu respect current node direction

---

lib/src/editor/editor_component/service/keyboard_service_widget.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/paste_command.dart
lib/src/editor/util/color_util.dart
lib/src/plugins/html/html_document_decoder.dart
test/plugins/html/html_document_test.dart

- Use the 'html' package to parse the raw HTML string.
- Parse the result into a document structure.
- When pasting, replace the current selection with the new nodes.
For a single DOM element, we only need to insert it at the selected position.
For multiple DOM elements, we should split the selected node, merge it into the parsed nodes, and then insert the parsed nodes before removing the selected one.

feat: paste from html

---

lib/src/editor/block_component/standard_block_components.dart
lib/src/editor/block_component/text_block_component/text_block_component.dart

Closes: #380
https://github.com/AppFlowy-IO/appflowy-editor/assets/42929161/f4b68051-28d6-4f76-ac66-cc6004de3577

fix: placeholder on paragraph when selected

---

lib/src/editor/toolbar/desktop/items/color/color_menu.dart

This pr solves issue #342 
Adding a variable to hold the selection temporarily while the user chooses a custom colour solves the issue.
Since the focus would have moved from the editor onto the colour, that's how the selection was lost.

fix: add variable to hold editor selection for colour menu

---

lib/src/core/location/selection.dart

Recently we have deprecated the the use of `selection.collapse()` and asked devs to use `selection.collapsed()` instead.
But the comment on `selection.collapsed()` suggests otherwise, this is confusing for the developer.
This PR removes the old comment on `selection.collapsed()` which asks the dev to use the `selection.collapse()` method.

chore: comment suggesting use of deprecated method

---

lib/src/editor/block_component/divider_block_component/divider_block_component.dart
lib/src/editor/block_component/divider_block_component/divider_character_shortcut.dart
test/new/block_component/bulleted_list_block_component/bulleted_list_character_shortcut_test.dart
test/new/block_component/divider_block_component/divider_character_shortcut_test.dart
test/new/block_component/heading_block_component/heading_character_shortcut_test.dart
test/new/block_component/numbered_list_block_component/numbered_list_character_shortcut_test.dart
test/new/block_component/quote_block_component/quote_character_shortcut_test.dart
test/new/block_component/test_character_shortcut.dart
test/new/block_component/todo_list_block_component/todo_list_character_shortcut_test.dart

fixes: #370 
Before:
After -
https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/0f0a2de1-533a-4356-8337-48323935b081

fix: fixed the cursor not moving to next line after inserting divider

---

example/macos/Runner.xcodeproj/project.pbxproj
example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
lib/src/plugins/html/encoder/delta_html_encoder.dart
test/plugins/html/encoder/parser/text_node_parser_test.dart

fix: html encoder not adding multiple text decorations

---

example/lib/pages/editor.dart
lib/src/editor/block_component/base_component/align_mixin.dart
lib/src/editor/block_component/base_component_keys.dart
lib/src/editor/block_component/block_component.dart
lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart
lib/src/editor/block_component/heading_block_component/heading_block_component.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/quote_block_component/quote_block_component.dart
lib/src/editor/block_component/rich_text/appflowy_rich_text.dart
lib/src/editor/block_component/text_block_component/text_block_component.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
lib/src/editor/toolbar/desktop/desktop.dart
lib/src/editor/toolbar/desktop/items/alignment_toolbar_items.dart

feat: support alignment for block component

---

lib/src/editor/block_component/table_block_component/table_block_component.dart
lib/src/editor/block_component/table_block_component/table_cell_block_component.dart
lib/src/editor/block_component/table_block_component/table_col.dart
lib/src/editor/block_component/table_block_component/table_col_border.dart
lib/src/editor/block_component/table_block_component/table_node.dart
test/new/block_component/table_block_component/table_view_test.dart

This should get merged after #432.

fix: better column resize performance

---

CHANGELOG.md
lib/src/editor/block_component/table_block_component/table_col.dart
lib/src/render/toolbar/toolbar_item.dart
pubspec.yaml

* feat: support table plugin by @zoli in ([#62](https://github.com/AppFlowy-IO/appflowy-editor/pull/62))
* feat: support alignment for block component by @LucasXu0 in ([#425](https://github.com/AppFlowy-IO/appflowy-editor/pull/425))
* feat: toggle highlight using ctrl/cmd + shift + h by @MayurSMahajan in ([#333](https://github.com/AppFlowy-IO/appflowy-editor/pull/333))
* feat: refactor floating toolbar positioning logic by @LucasXu0 in ([#422](https://github.com/AppFlowy-IO/appflowy-editor/pull/42))
* feat: default text direction property by @zoli in ([#402](https://github.com/AppFlowy-IO/appflowy-editor/pull/402))
* fix: rect of the divider block is incorrect by @LucasXu0 in ([#415](https://github.com/AppFlowy-IO/appflowy-editor/pull/415))
* fix: replace matches on the same node by …

chore: bump version 1.3.0

---

lib/src/core/document/node.dart
lib/src/core/document/text_delta.dart
pubspec.yaml
test/core/document/text_delta_test.dart

- Provide ExternalValues to save the external values that are not defined in the node.
- Implement Delta Diff

feat: implement delta diff and provide external values

---

lib/src/editor/find_replace_menu/find_replace_widget.dart

This PR includes a workaround to keep focus after submitting in the find/replace text fields, otherwise the focus is forced on the editor due to the interactions required.

fix: request focus in find replace menu

---

lib/src/editor/block_component/standard_block_components.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/command_shortcut_events.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/open_links_command.dart
test/new/service/shortcuts/command_shortcut_events/open_links_comand_test.dart

Created a keyboard shortcut to bulk open selected links in a document. 
Reference issue: [#2323](https://github.com/AppFlowy-IO/AppFlowy/issues/2323)

feat: bulk open links shortcut

---

lib/src/editor/block_component/base_component/background_color_mixin.dart
lib/src/editor/block_component/rich_text/appflowy_rich_text.dart
lib/src/editor/block_component/table_block_component/table_cell_block_component.dart
lib/src/editor/toolbar/desktop/items/color/color_picker.dart
lib/src/editor/toolbar/mobile/toolbar_items/color/utils/color_button.dart
lib/src/editor/util/color_util.dart
test/editor/util/color_util_test.dart
test/extensions/color_extension_test.dart

Support some color formats.
- rgb
- rgba
- 0x(6-8)
- #(6)

Refactor color conversion method to handle RGB and hex formatsRefactor method to handle RGB and hex formats, improving color conversion

---

lib/src/editor/block_component/table_block_component/table_action.dart
test/new/block_component/table_block_component/table_action_test.dart

Close #469 .
Delete the whole `tableNode` when calling `_deleteRow` or `deleteCol` on the last row/column.

fix: resolve `RangeError`when last row deleted.

---

lib/src/editor/editor_component/service/scroll_service_widget.dart
lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
lib/src/render/selection/mobile_selection_widget.dart

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/66e95e9a-f40d-4006-9cca-93b9de9e8bf2

feat: adjust the loading large document optimization in mobile platform

---

lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/backspace_command.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/delete_command.dart
lib/src/extensions/node_extensions.dart

Close #465 .
This occurred because the table was not deleted, instead, the paragraph in the first cell was deleted. As a result, no child elements could be found in the cell when building the table (and thus throws "bad state, no element").
I'm not sure if this is the right way. If this fix is not correct or not the best practice, please make any suggestions or modifications, or, of course, close it.

fix: resolve "Bad state: no element" when in-table paragraph deleted

---

lib/src/editor/editor_component/service/selection/mobile_selection_service.dart

bug screen record:
when you drag left handler first, then you drag right handler will cause this bug, selection changed wrong.
fixed:

fix: fix mobile selection drag

---

lib/src/editor/block_component/image_block_component/image_block_component.dart
lib/src/editor/block_component/image_block_component/resizable_image.dart
lib/src/plugins/html/html_document_decoder.dart
test/plugins/html/html_document_test.dart

fix: the text within the <mark> tag didn't parse correctly when pasting HTML

---

lib/src/core/document/node.dart
lib/src/editor_state.dart
test/new/service/shortcuts/command_shortcut_events/undo_redo_command_test.dart

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/f09241e8-2b91-411e-ba09-54c55e75dc8b
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/6bed3527-3f54-4c5d-916b-2afb6a4ad53e
thanks @r3velated for providing the reproduction steps.

fix: undo failed in a nested list in a special case

---

example/lib/home_page.dart
example/lib/pages/focus_example_for_editor.dart
lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
test/customer/text_field_and_editor_test.dart

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/2310f887-a4c9-4a66-ac9e-66f099a818f6

fix: unable to update selection sometimes when the editor lost focus

---

example/lib/pages/desktop_editor.dart
lib/src/editor/toolbar/desktop/floating_toolbar.dart
lib/src/editor/toolbar/desktop/floating_toolbar_widget.dart
test/customer/custom_toolbar_item_color_test.dart
test/new/infra/testable_editor.dart
test/new/service/shortcuts/command_shortcut_events/show_link_menu_command_test.dart
test/new/toolbar/desktop/floating_toolbar_test.dart

FR raised here also :
https://github.com/AppFlowy-IO/AppFlowy/issues/3481

support RTL in toolbar

---

example/lib/pages/desktop_editor.dart
lib/src/editor/editor_component/service/scroll_service_widget.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/find_replace_command.dart
lib/src/editor/find_replace_menu/find_menu_service.dart
lib/src/editor/find_replace_menu/find_replace_menu_icon_button.dart
lib/src/editor/find_replace_menu/find_replace_widget.dart
lib/src/editor/find_replace_menu/search_service.dart
lib/src/editor/find_replace_menu/search_service_v2.dart
lib/src/editor/toolbar/desktop/floating_toolbar.dart
lib/src/editor_state.dart
test/new/find_replace_menu/find_replace_menu_find_test.dart
test/new/find_replace_menu/find_replace_menu_replace_test.dart
test/new/find_replace_menu/find_replace_menu_utils.dart

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/14230499-5818-4aa3-90e9-23b20d1df5da

feat: optimize the find and replace logic

---

lib/src/editor/editor_component/service/selection/desktop_selection_service.dart

Closes: #31 
Closes: https://github.com/AppFlowy-IO/AppFlowy/issues/3579

feat: enable shift+press for selection range

---

lib/src/editor/block_component/base_component/insert_newline_in_type_command.dart
lib/src/editor/block_component/heading_block_component/heading_character_shortcut.dart
lib/src/editor/block_component/standard_block_components.dart
lib/src/editor/editor_component/service/renderer/block_component_service.dart
lib/src/editor/editor_component/service/shortcuts/character_shortcut_events/slash_command.dart
test/customer/custom_error_block_test.dart

Provide an 'errorBlockComponentBuilderKey' to allow developers to customize the error handler when an error occurs in the block.
```dart
AppFlowyEditor(
editorState: editorState,
blockComponentBuilders: {
...standardBlockComponentBuilderMap,
errorBlockComponentBuilderKey:
ErrorBlockComponentBuilder(),
},
),
```

feat: support customizing error block

---

example/lib/pages/focus_example_for_editor.dart
lib/src/editor/block_component/base_component/widget/ignore_parent_gesture.dart
lib/src/editor/editor_component/entry/page_block_component.dart
lib/src/editor/editor_component/service/selection/desktop_selection_service.dart

fix: the selection should be clear if header or footer is focusing

---

lib/src/editor/editor_component/service/selection/mobile_selection_service.dart

fix: the selection handles remain on the screen after cutting the text

---

CHANGELOG.md
pubspec.yaml

* feat: support customizing error block by @LucasXu0 in ([#524](https://github.com/AppFlowy-IO/appflowy-editor/pull/524))
* feat: export JSON in mobile and update mobile_example.json by @hyj1204 in ([#515](https://github.com/AppFlowy-IO/appflowy-editor/pull/515))
* feat: add regex and case sensitive to `FindReplaceMenu` by @sun-jiao in ([#480](https://github.com/AppFlowy-IO/appflowy-editor/pull/480))
* feat: customize desktop toolbar style by @q200892907 in ([#519](https://github.com/AppFlowy-IO/appflowy-editor/pull/519))
* feat: support RTL in toolbar by @1akhanBaheti in ([#496](https://github.com/AppFlowy-IO/appflowy-editor/pull/496))
* feat: optimize the find and replace logic by @LucasXu0 in ([#510](https://github.com/AppFlowy-IO/appflowy-editor/pull/510))
* feat: enable shift+press …

chore: bump version 1.4.4

---

lib/src/core/transform/transaction.dart
lib/src/editor/block_component/rich_text/appflowy_rich_text_keys.dart
lib/src/editor/command/text_commands.dart
lib/src/editor/editor_component/service/ime/delta_input_on_insert_impl.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/markdown_commands.dart
lib/src/editor_state.dart
test/new/command/text_commands_test.dart

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/6a4ff165-33a8-4b38-833d-4f2373135933
- toggling the bold/underline/italic/strikethrough via cmd/ctrl + b/u/i/shift+s when the selection is collapsed.
- canceling the bold/underline/italic/strikethrough via cmd/ctrl + b/u/i/shift+s when the selection is collapsed.

feat: enable toggling and canceling of the formatting with shortcuts

---

lib/src/editor/block_component/base_component/selection/block_selection_area.dart

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/101e6c3b-1b5e-4827-8194-ca5589d8cef4
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/9f782d84-6af7-44e6-9e89-c439f2962e8f

fix: cursor blink at wrong location when inserting text

---

example/lib/pages/mobile_editor.dart
lib/src/editor/block_component/base_component/selection/block_selection_container.dart
lib/src/editor/block_component/block_component.dart
lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart
lib/src/editor/block_component/heading_block_component/heading_block_component.dart
lib/src/editor/block_component/image_block_component/image_upload_widget.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/paragraph_block_component/paragraph_block_component.dart
lib/src/editor/block_component/quote_block_component/quote_block_component.dart
lib/src/editor/block_component/standard_block_components.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
lib/src/editor/editor_component/service/editor.dart
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/editor_component/service/keyboard_service_widget.dart
lib/src/editor/editor_component/service/shortcuts/character_shortcut_events/slash_command.dart
lib/src/editor/selection_menu/selection_menu_widget.dart
lib/src/editor/toolbar/desktop/items/color/color_menu.dart
lib/src/editor/toolbar/desktop/items/link/link_toolbar_item.dart
test/customer/custom_action_builder_test.dart
test/customer/text_field_and_editor_test.dart

- the cursor will be blocked if the background color of the text isn't transparent.
- expand the background color of the block component

fix: UI issues

---

lib/src/plugins/markdown/encoder/document_markdown_encoder.dart
lib/src/plugins/markdown/encoder/parser/bulleted_list_node_parser.dart
lib/src/plugins/markdown/encoder/parser/code_block_node_parser.dart
lib/src/plugins/markdown/encoder/parser/heading_node_parser.dart
lib/src/plugins/markdown/encoder/parser/image_node_parser.dart
lib/src/plugins/markdown/encoder/parser/node_parser.dart
lib/src/plugins/markdown/encoder/parser/numbered_list_node_parser.dart
lib/src/plugins/markdown/encoder/parser/quote_node_parser.dart
lib/src/plugins/markdown/encoder/parser/table_node_parser.dart
lib/src/plugins/markdown/encoder/parser/text_node_parser.dart
lib/src/plugins/markdown/encoder/parser/todo_list_node_parser.dart
test/plugins/markdown/document_markdown_test.dart
test/plugins/markdown/encoder/document_markdown_encoder_test.dart
test/plugins/markdown/encoder/parser/image_node_parser_test.dart
test/plugins/markdown/encoder/parser/table_node_parser_test.dart
test/plugins/markdown/encoder/parser/text_node_parser_test.dart

feat: support parsing the nested list when exporting the document to markdown format

---

lib/src/plugins/html/encoder/parser/html_parser.dart
lib/src/plugins/html/encoder/parser/table_node_parser.dart
lib/src/plugins/html/html_document.dart
lib/src/plugins/html/html_document_decoder.dart
test/plugins/html/decoder/document_html_decoder_test.dart
test/plugins/html/encoder/document_html_encoder_test.dart
test/plugins/html/encoder/parser/image_node_parser_test.dart
test/plugins/html/encoder/parser/table_node_parser_test.dart
test/plugins/html/encoder/parser/text_node_parser_test.dart

feat: table html encoder and decoder added

---

lib/src/editor/command/text_commands.dart
lib/src/editor_state.dart

feat: toggledStyle notifier

---

lib/src/editor/block_component/standard_block_components.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
test/new/block_component/todo_list_block_component/todo_list_power_toggle_test.dart

Add an easy way to add LogicalKeyboardKey triggers to the Todo Block, to power toggle a checkbox, which toggles all of it's children to the same state of the todo that is toggled.
https://github.com/AppFlowy-IO/appflowy-editor/assets/42929161/da5b9854-d023-4912-96de-ed97e3305e9a

feat: power checkbox shortcut

---

lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
lib/src/editor_state.dart
test/service/selection_service_test.dart

By resetting the SelectionType on `SelectionUpdateReason.uiEvent`, when a Block is selected with the type `SelectionType.block`, you can cancel it by making a new selection (pressing).

fix: on ui event reset selection type

---

lib/src/editor/editor_component/entry/page_block_component.dart
test/editor/editor_test.dart

fix: check if header exists for footer

---

lib/src/editor/toolbar/mobile/mobile_floating_toolbar/mobile_floating_toolbar.dart
lib/src/editor/toolbar/mobile/mobile_toolbar.dart
lib/src/render/selection/mobile_selection_widget.dart

closes [#554](https://github.com/AppFlowy-IO/appflowy-editor/issues/554)
closes #548

fix: quit editing button doesn't work

---

lib/src/editor/editor_component/service/keyboard_service_widget.dart
lib/src/editor/editor_component/service/shortcuts/command/arrow_left_command.dart
lib/src/editor/editor_component/service/shortcuts/command/arrow_right_command.dart

Solve the left and right key bug. When adding an input box at the head or tail of the editor, it cannot be moved.

fix:Solve the left and right key bug. 

---

CHANGELOG.md
pubspec.yaml

* feat: support Flutter stable channel by @LucasXu0 in ([#581](https://github.com/AppFlowy-IO/appflowy-editor/pull/581))
* feat: support toggling format style when the selection is collapsed by @LucasXu0 in ([#586](https://github.com/AppFlowy-IO/appflowy-editor/pull/586))
* fix: don't rebuild mobile toolbar every time by @LucasXu0 in ([#579](https://github.com/AppFlowy-IO/appflowy-editor/pull/579))
* fix: solve the left and right key bug by @q200892907 in ([#584](https://github.com/AppFlowy-IO/appflowy-editor/pull/584))

chore: bump version 2.0.0

---

lib/src/editor/selection_menu/selection_menu_service.dart

part of https://github.com/AppFlowy-IO/AppFlowy/issues/3414.
The problem was presupposing that the editor width equal to the application width. So when there was something like a sidebar in AppFlowy the calculations were going wrong.
There will be still issues with the selection menu because the width is too long. It should get shorter and other items should get access through scroll. 
Personally, I prefer a vertical menu rather than a horizontal one.

fix: selection menu positioning on right half of editor

---

lib/src/editor/toolbar/desktop/floating_toolbar.dart

```dart
import 'package:appflowy_editor/appflowy_editor.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
class DesktopEditor extends StatefulWidget {
const DesktopEditor({
super.key,
required this.editorState,
this.textDirection = TextDirection.ltr,
});
final EditorState editorState;
final TextDirection textDirection;
@override
State<DesktopEditor> createState() => _DesktopEditorState();
}
class _DesktopEditorState extends State<DesktopEditor> {
EditorState get editorState => widget.editorState;
late final EditorScrollController editorScrollController;
late EditorStyle editorStyle;
late Map<String, BlockComponentBuilder> blockComponentBuilders;
late List<CommandShortcutEvent> commandShortcuts;
@override
void initState() {
super.initState(); …
```

feat:floating_toolbar_position_error

---

lib/src/plugins/markdown/decoder/document_markdown_decoder.dart
test/plugins/markdown/decoder/document_markdown_decoder_test.dart

fixes #398 and https://github.com/AppFlowy-IO/AppFlowy/issues/2809
Demo:

fix: markdown does not support nested lists

---

lib/src/editor/block_component/base_component/widget/ignore_parent_gesture.dart
lib/src/editor/editor_component/service/shortcuts/command/cut_command.dart
lib/src/editor/editor_component/service/shortcuts/command/select_all_command.dart
lib/src/editor/editor_component/service/shortcuts/command/undo_redo_command.dart

https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/f095809d-c430-452d-99e9-eeac8fe54c3b
#542

fix: header/footer focus issue

---

lib/src/editor/editor_component/service/shortcuts/command/paste_command.dart

Renamed the key **"paste the content"** for shortcut `ctrl+shift+v` to **"paste the content as plain text"**
this PR is related to [[Bug] Duplicate commands and key bindings in Shortcuts menu #4193](https://github.com/AppFlowy-IO/AppFlowy/issues/4193)

fix: renamed duplicated shortcut key

---

example/lib/pages/desktop_editor.dart
lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart
lib/src/editor/block_component/heading_block_component/heading_block_component.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/paragraph_block_component/paragraph_block_component.dart
lib/src/editor/block_component/quote_block_component/quote_block_component.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
lib/src/editor/editor_component/style/editor_style.dart

feat: support customizing cursor width

---

lib/src/editor/editor_component/service/ime/delta_input_on_floating_cursor_update.dart
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/editor_component/service/ime/text_input_service.dart
lib/src/editor/editor_component/service/keyboard_service_widget.dart
lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
lib/src/render/selection/mobile_basic_handle.dart

closes https://github.com/AppFlowy-IO/appflowy-editor/issues/651
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/c999723f-eb36-4597-bfe3-0740abe9af51

feat: support updating cursor position via spacebar

---

lib/src/editor/editor_component/service/ime/delta_input_on_non_text_update_impl.dart

#610  test window/linux @LucasXu0

fix:chinese input 610

---

lib/src/editor/block_component/base_component/widget/ignore_parent_gesture.dart

Solve the focus problem caused by monitoring onFocusChange and change to monitoring click events
https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/bc669f32-d70b-4059-9bf0-484f426291dd

fix: ignore_parent_gesture

---

lib/src/editor/editor_component/service/ime/non_delta_input_service.dart

Solve the problem that Chinese ime cannot continue deleting after deleting input content
Before
https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/5d7a684a-c61f-4e82-882a-f86c30f3c76a
After
https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/2fc1d886-10d8-49c1-a8d2-e7c151936002

fix:Solve the problem that Chinese ime cannot continue deleting after deleting input content

---

lib/src/editor/editor_component/service/ime/delta_input_on_insert_impl.dart
lib/src/editor/editor_component/service/shortcuts/character/format_single_character/format_single_character.dart
test/new/editor_component/service/shortcuts/character_shortcuts/back_slash_igore_format_test.dart

To close
https://github.com/AppFlowy-IO/AppFlowy/issues/3628
https://github.com/AppFlowy-IO/AppFlowy/issues/3964
Add the ability to ignore the `CharacterShortcutEvent`
Use `\` to skip all the markdown style
**For the wrapped style shortcut events**
like \_abc_   \**abc**  \__abc__  \~~abc~~  \`abc`
Put `\` in front of the enable character. 
https://github.com/AppFlowy-IO/appflowy-editor/assets/14248245/a6546c46-6890-4485-afd7-b1f5759c7a3b
**For the space enabled shortcut events**
like - abc, " abc, > abc, # abc, -[] ABC
Put `\` in front of the character before the space
https://github.com/AppFlowy-IO/appflowy-editor/assets/14248245/af3ea7ec-55c4-4ede-b38e-c109ff40a131

feat: backslash to ignore shortcut event

---

lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
lib/src/editor/toolbar/mobile/mobile_floating_toolbar/mobile_floating_toolbar.dart
lib/src/render/selection/mobile_basic_handle.dart

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/06631113-bfe1-43ed-869f-c7e20bd12f6d
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/88ca5550-c9f7-47d5-9ced-a8ff5f4a0881

fix: the magnifier doesn't disappear when the selection is collapsed

---

lib/src/editor/block_component/heading_block_component/heading_block_component.dart

fix: headingBlockComponentBuilder doesn't use placeholderTextStyle

---

lib/src/plugins/markdown/decoder/document_markdown_decoder.dart
test/plugins/markdown/decoder/document_markdown_decoder_test.dart

Hello :wave:
First of all, I would like to thank you for building this library and taking the time to maintain the editor separately from the application. I have been waiting for a good rich text editor in Flutter for a long time.
Since this is my first contribution to the project, please tell me if I missed any guidelines that I should have followed.
I skimmed the documentation on contributing, but thought I would just get my feet wet and start with a pull request for a small change.
Now on to the actual content of the PR:
The markdown parser doesn't currently handle nested numbered lists.
Nested bullet lists and todo lists work fine, but numbered lists don't.
I made the necessary changes to parse nested numbered lists.
I also modified a test for nested lists to include a numbered list.

feat: parse nested numbered list

---

lib/src/editor/block_component/base_component/insert_newline_in_type_command.dart
test/editor/block_component/base_component/insert_newline_in_type_command_test.dart
test/new/service/shortcuts/command_shortcut_events/enter_without_shift_in_text_node_handler_test.dart

Modify the operation of the Enter key for list type blocks. If it is empty, perform the Shift+Tab operation until it returns to no format.
https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/8a79f151-50af-4d04-b60d-5ecfbdf34943

feat:Optimize Enter operation

---

lib/src/plugins/markdown/decoder/delta_markdown_decoder.dart
pubspec.yaml

Closes: #678 
Resolves an issue where the local markdown version is higher than `7.1.0` which causes an API mismatch.

fix: upgrade markdown to 7.2.1

---

documentation/testing.md
lib/src/editor/editor_component/service/shortcuts/command/copy_paste_extension.dart
test/new/service/shortcuts/command_shortcut_events/paste_command_test.dart

closes: https://github.com/AppFlowy-IO/appflowy-editor/issues/679
closes: https://github.com/AppFlowy-IO/AppFlowy/issues/4421

Fix: pasting keeps current node

---

example/pubspec.yaml
lib/src/editor/editor_component/service/editor.dart
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/editor_component/service/ime/text_input_service.dart
lib/src/editor/editor_component/service/keyboard_service_widget.dart
test/editor/editor_component/ime/non_delta_input_service_test.dart

This PR Adds support for  `contentInsertionConfiguration` attribute that allows the usage of Android's [image keyboard](https://developer.android.com/develop/ui/views/touch-and-input/image-keyboard) to Flutter.
See: https://api.flutter.dev/flutter/material/TextField/contentInsertionConfiguration.html
This will allow the handling of more complex clipboard contents pastes (like images), or insertion of gifs and stickers
Linked issue: https://github.com/AppFlowy-IO/appflowy-editor/issues/646

feat: Add contentInsertionConfiguration to editor and text input service

---

example/lib/home_page.dart
example/lib/pages/editor.dart
lib/src/editor_state.dart
lib/src/plugins/plugins.dart
lib/src/plugins/word_count/word_counter_service.dart
test/plugins/word_count/word_counter_test.dart

My first idea was to setup a listener to the Transaction stream of the EditorState, and then update the counters only with the changeset, but this seems not quite possible with how operations currently work.
Currently, an UpdateOperation contains inserts in the delta, and whilst we do have the old attributes to compare against, it seems that it can happen that the new attributes delta can be a subset of the old one, causing it to be near impossible to rely on the difference in characters and words as the comparison of the two might not be representative of the actual changes to the document.
We can improve and build on this (eg. add Selection word/char count to the service) in the future.

feat: word counter service

---

lib/src/editor/block_component/table_block_component/table_action_menu.dart
lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
lib/src/editor/find_replace_menu/find_menu_service.dart
lib/src/editor/selection_menu/selection_menu_service.dart
lib/src/editor/toolbar/desktop/floating_toolbar.dart
lib/src/editor/toolbar/desktop/items/color/color_menu.dart
lib/src/editor/toolbar/desktop/items/link/link_toolbar_item.dart
lib/src/editor/toolbar/mobile/mobile_floating_toolbar/mobile_floating_toolbar.dart
test/customer/editor_on_overlay_test.dart

While developing with AppFlowy editor, I encountered the following bug in the web version. I have integrated the AppFlowy editor into my app as shown in the image. On the left side, the editor is positioned between a sidebar and a header. This placement causes a displacement of the command menu. The slippage occurs because the menu is inserted relative to its container, rather than being positioned absolutely within the web page.
The command menu should be positioned correctly without any slippage, even when the editor is placed between a sidebar and a header.
To resolve this issue, I modified Overlay.of(context) to Overlay.of(context, rootOverlay: true). Additionally, this fix also addresses issue #545.
Please review and consider implementing this fix in the next release. Let me know if …

fix: Slash command menu bad positioning in Web Version

---

example/devtools_options.yaml
example/lib/home_page.dart
example/lib/pages/mobile_editor.dart
lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/quote_block_component/quote_block_component.dart
lib/src/editor/block_component/rich_text/appflowy_rich_text.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
lib/src/editor/editor_component/style/editor_style.dart
lib/src/infra/flowy_svg.dart

feat: support scaling the svg

---

lib/src/editor/block_component/base_component/markdown_format_helper.dart
lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_character_shortcut.dart
lib/src/editor/block_component/heading_block_component/heading_character_shortcut.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_character_shortcut.dart
lib/src/editor/block_component/quote_block_component/quote_character_shortcut.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_character_shortcut.dart
test/new/block_component/bulleted_list_block_component/bulleted_list_character_shortcut_test.dart
test/new/block_component/heading_block_component/heading_character_shortcut_test.dart
test/new/block_component/numbered_list_block_component/numbered_list_character_shortcut_test.dart
test/new/block_component/test_character_shortcut.dart
test/new/block_component/todo_list_block_component/todo_list_character_shortcut_test.dart
test/plugins/quill_delta/quill_delta_encoder_test.dart

closes https://github.com/AppFlowy-IO/AppFlowy/issues/4492

fix: resolve data loss issue during block type conversion

---

lib/src/editor/editor_component/service/shortcuts/command/paste_command.dart
test/new/service/shortcuts/command_shortcut_events/paste_command_test.dart

https://github.com/AppFlowy-IO/appflowy-editor/issues/693
1. detect the text with url regrex
2. if there is a url exist, split the text into three parts. The first part and the final part may not exist.add url attribute for the url part.
3. if there is no url exist,just return the text.
unit test: all pass.

fix: transfer the whole line into link when text contains url (#693)

---

CHANGELOG.md
pubspec.yaml

CC @LucasXu0 - I don't have a verified publisher account, I'll leave it to you.

chore: bump version 2.3.3

---

lib/src/editor/block_component/table_block_component/table_action_handler.dart

fIx: Table Icon visible on hover in Editable and causes exception when clicked  [Bug]   (issue (#717) )
* fix:  Check visible Widget TableActionHandler when widget.editorState.editable == true
* Update:  lib/src/editor/block_component/table_block_component/table_action_handler.dart

fIx: TableActionHandler editorState.editable  [Bug]  (issue (#717) )

---

lib/src/editor/block_component/heading_block_component/heading_block_component.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_character_shortcut.dart
test/new/block_component/numbered_list_block_component/numbered_list_character_shortcut_test.dart

https://github.com/AppFlowy-IO/AppFlowy/issues/4853

feat: disable converting heading block to numbered list block

---

lib/src/editor/block_component/rich_text/appflowy_rich_text.dart

```log
I/flutter (11040): LateInitializationError: Local 'result' has not been initialized.
I/flutter (11040): #0      LateError._throwLocalNotInitialized (dart:_internal-patch/internal_patch.dart:189)
I/flutter (11040): #1      RenderObject.debugNeedsLayout (package:flutter/src/rendering/object.dart:2183)
I/flutter (11040): #2      _AppFlowyRichTextState.getCursorRectInPosition (package:appflowy_editor/src/editor/block_component/rich_text/appflowy_rich_text.dart:154)
I/flutter (11040): #3      DefaultSelectableMixin.getCursorRectInPosition (package:appflowy_editor/src/editor/block_component/rich_text/default_selectable_mixin.dart:48)
I/flutter (11040): #4      KeyboardServiceWidgetState._updateCaretPosition (package:appflowy_editor/src/editor/editor_component/service/keyboard_service_widg …
```

fix: late initialization error

---

lib/src/core/document/diff.dart
test/core/document/diff_test.dart

Combine consecutive insert or delete operations. 
For example, 'insert p1, v1; insert p2, v2; ...' should be combined into 'insert p1, [v1, v2, ...]'.

feat: combine diff operations

---

.github/workflows/test.yml
example/lib/home_page.dart
example/lib/pages/auto_complete_editor.dart
example/lib/pages/desktop_editor.dart
lib/src/editor/block_component/base_component/auto_complete_command.dart
lib/src/editor/block_component/base_component/text_style_configuration.dart
lib/src/editor/block_component/block_component.dart
lib/src/editor/block_component/rich_text/appflowy_rich_text.dart
lib/src/editor/block_component/rich_text/appflowy_rich_text_keys.dart
lib/src/editor/editor_component/service/editor.dart
lib/src/editor_state.dart
test/customer/auto_complete_test.dart

- Added support for the basic auto-complete functionality.
- Added a showcase, please refer to the video.
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/d6ae9c7a-51a1-4dc6-8a38-8b6ea3bdc838

feat: support auto complete for text block

---

lib/src/editor/block_component/rich_text/appflowy_rich_text.dart
lib/src/editor/block_component/table_block_component/table_block_component.dart
lib/src/editor/block_component/table_block_component/table_col.dart
lib/src/editor/block_component/table_block_component/table_config.dart
lib/src/editor/block_component/table_block_component/table_node.dart
lib/src/editor/block_component/table_block_component/table_view.dart
test/new/block_component/table_block_component/table_node_test.dart

add table style
Default width and height can be customized

feat:add table style

---

example/lib/pages/customize_theme_for_editor.dart
lib/src/editor/block_component/base_component/text_style_configuration.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/rich_text/appflowy_rich_text.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
test/customer/custom_block_icon_test.dart

- added support for customizing the line height params: applyHeightToFirstAscent and applyHeightToLastDescent.
- optimize the list icon builder.

feat: support customizing mobile page style

---

example/pubspec.yaml
lib/src/infra/clipboard.dart
pubspec.yaml
test/plugins/word_count/word_counter_test.dart

Breaking change: The copy/paste HTML functionality has been removed. It'll be transferred to [appflowy-plugins](https://github.com/AppFlowy-IO/appflowy-plugins).
Related issue: https://github.com/BringingFire/rich_clipboard/issues/25

chore: upgrade flutter dependencies

---

lib/src/editor/block_component/rich_text/appflowy_rich_text.dart
lib/src/editor/block_component/rich_text/default_selectable_mixin.dart
lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
lib/src/editor/toolbar/mobile/mobile_floating_toolbar/mobile_floating_toolbar.dart
lib/src/render/selection/selectable.dart

|Interaction| Android | iOS |
|:---:| :---:|:---:|
| tap | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/33f9beec-d20c-40f7-b55c-4368fa22c308"> |<video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/b6d5f473-6c9a-4861-a206-fd5991039acd">|
| double tap | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/62186fd7-ed77-4c96-9350-44d66961fed6"> | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/1f640fcf-3c15-4b67-a5b6-8cdea26407e8">|
| triple tap | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/d49c95c1-1cdc-41ee-88b4-fd82a15129a8"> | <video src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71320345/b0215a82-1b6a-47a3-893b-6d4ed98b2d27"> |
| long press + …

feat: improve mobile selection

---

lib/src/editor/toolbar/desktop/items/link/link_toolbar_item.dart

fix: improve link menu position

---

lib/src/extensions/position_extension.dart

fixes #745 
Previously the `moveVertical` function only moved the cursor 'node to node' without taking into consideration multiline nodes or some portion of a line with different fontSize (ex: a paragraph with size 16 but with a bolded word with size 32). This was caused by the PR #657 that closes #656 and #589.

fix: incorrect cursor movement behaviour

---

lib/src/editor/block_component/rich_text/appflowy_rich_text.dart

To retrieve consistent cursor height after upgrading to Flutter 3.22, set forceStrutHeight to true. 
closes https://github.com/AppFlowy-IO/appflowy-editor/issues/804

fix: cursor height is not consistent

---

example/lib/home_page.dart
example/lib/main.dart
lib/src/editor/toolbar/mobile/mobile_toolbar_v2.dart

close https://github.com/AppFlowy-IO/appflowy-editor/issues/815
set the `maintainBottomViewPadding` to `true`. This ensures that any bottom padding (like the one provided by MediaQuery) is maintained when the keyboard is displayed.

fix: mobile toolbar UI shift

---

lib/src/editor/block_component/table_block_component/table_commands.dart
lib/src/editor/editor_component/service/shortcuts/command_shortcut_event.dart

- Enables clearing a command
- Makes table commands public so we can consume then to eg. localize by the `command.key`

feat: command improvement

---

lib/src/editor/find_replace_menu/find_replace_widget.dart
lib/src/editor/find_replace_menu/search_service_v3.dart

Partially solves: [#5491](https://github.com/AppFlowy-IO/AppFlowy/issues/5491)
- Removes code that triggers `jumpTo()` call. This can be removed since, making a selection implicitly causes the editor to scroll to the new selection.
- Remove unused variables
Preview:
- For given user sample (small text)
https://github.com/AppFlowy-IO/appflowy-editor/assets/47064215/7c5093b7-6c08-4dd8-bbf5-9145a92cb40a
- For long text sample
https://github.com/AppFlowy-IO/appflowy-editor/assets/47064215/d55713c1-991c-4e79-b053-23d632e58414
Additional Context:
https://github.com/AppFlowy-IO/AppFlowy/issues/5491#issuecomment-2166388521

fix: content jumping down and scrolling getting locked.

---

lib/src/editor/editor_component/service/shortcuts/character/format_single_character/format_single_character.dart

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Not in inclusive range 4..5: -1
#0      RangeError.checkValidRange (dart:core/errors.dart:365:9)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:418:27)
#2      _OpIterator.next (package:appflowy_editor/src/core/document/text_delta.dart:591:23)
#3      Delta.compose (package:appflowy_editor/src/core/document/text_delta.dart:277:33)
#4      TextTransaction.compose.<anonymous closure> (package:appflowy_editor/src/core/transform/transaction.dart:568:59)
#5      ListBase.fold (dart:collection/list.dart:202:22)
#6      TextTransaction.compose (package:appflowy_editor/src/core/transform/transaction.dart:568:22)
#7      Transaction.operations …
```

fix: underscore markdown syntax assertion

---

lib/src/editor/block_component/rich_text/appflowy_rich_text.dart

There's a breaking change in Flutter 3.22.x
The `getFullHeightForCaret` didn't respect the font size anymore if it's in the sub level
```dart
RichText(
key: richTextKey,
text: const TextSpan(
children: [
TextSpan(
text: 'AppFlowy ',
style: TextStyle(
inherit: true,
color: Color(0xff000000),
fontSize: 16.0,
decoration: TextDecoration.none,
),
),
TextSpan(
text: ' Editor',
style: TextStyle(
inherit: true,
color: Color(0xff000000),
fontSize: 20.0,
decoration: TextDecoration.none,
),
),
],
),
```
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/8892bcba-fa02-4c38-8546-e2442ac0dea7
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/86871f04-1baf-4dcb-a7a2-e226d3561574
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/b98255e0-b433-4c53-a9e2-d64da1fd0218 …

fix: cursor height is inconsistent after upgrading to Flutter 3.22

---

.github/workflows/test.yml

The macos 11 runner has been removed in github action.
https://github.com/actions/runner-images/issues/9255

chore: remove macos runner 11 in test ci

---

lib/src/extensions/position_extension.dart

fix: incorrect calculation of skip value in moveVertical

---

example/lib/pages/markdown/markdown_code_block_parser.dart
lib/src/editor/block_component/table_block_component/table_action_handler.dart
lib/src/editor/block_component/table_block_component/table_block_component.dart
lib/src/editor/block_component/table_block_component/table_col.dart
lib/src/editor/block_component/table_block_component/table_col_border.dart
lib/src/editor/block_component/table_block_component/table_node.dart
lib/src/plugins/markdown/decoder/document_markdown_decoder.dart
lib/src/plugins/markdown/decoder/parser/custom_markdown_node_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_block_quote_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_divider_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_heading_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_image_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_ordered_list_item_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_ordered_list_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_paragraph_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_parser_extension.dart
lib/src/plugins/markdown/decoder/parser/markdown_table_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_todo_list_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_unordered_list_item_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_unordered_list_parser.dart
test/new/block_component/table_block_component/table_view_test.dart
test/plugins/html/decoder/document_html_decoder_test.dart
test/plugins/markdown/decoder/table_decoder_test.dart
test/plugins/markdown/markdown_customer_test.dart

Make sure the numbers are the same as in the markdown.

fix: render issue of nested list

---

lib/src/editor/toolbar/mobile/mobile_toolbar_v2.dart
lib/src/editor/toolbar/mobile/utils/keyboard_height_observer.dart

fix: the toolbar will be blocked if the scroll bar is hidden

---

example/lib/pages/markdown/markdown_code_block_parser.dart
example/test/markdown_code_block_parser_test.dart
lib/src/plugins/markdown/decoder/document_markdown_decoder.dart

Remove the html escape text when parsing markdown to document.

fix: document from markdown contains html escape text

---

lib/src/editor/editor_component/service/selection/desktop_selection_service.dart

It seems I forgot to translate the offsets to global coordinates of the selectable rect, so the `isCloserToStart` was not correct. Now there's a point halfway in a block in the Y-axis where the drop target will move to the next node, which is more smooth.

fix: refine drop target position

---

lib/src/editor/editor_component/service/editor.dart

We can disable the selection, keyboard, and scroll services when in read-only mode.

feat: support disabling keyboard & scroll service

---

lib/src/editor/editor_component/service/renderer/block_component_widget.dart

https://github.com/AppFlowy-IO/AppFlowy/issues/5876

fix: stabilize rendering for nested lists beyond level 1

---

lib/src/editor/selection_menu/selection_menu_widget.dart

Use `iconBuilder` in SelectionMenuItem.node to customize your own icon.

feat: allow optional icon builder for selection menu items

---

lib/src/editor/selection_menu/selection_menu_item_widget.dart
lib/src/editor/selection_menu/selection_menu_widget.dart

Use `SelectionMenuItemNameBuilder` to customize the font family.

feat: custom slash menu text style

---

lib/src/editor/toolbar/desktop/items/bulleted_list_toolbar_item.dart
lib/src/editor/toolbar/desktop/items/numbered_list_toolbar_item.dart
test/new/toolbar/desktop/floating_toolbar_test.dart

currently, it's only possible to convert a single line to a bullet or numbered list.
changed the active check function to also show list items in toolbar when multiple text lines are selected.
closes https://github.com/AppFlowy-IO/AppFlowy/issues/3181

fix: enable converting multilne to list

---

CHANGELOG.md
lib/appflowy_editor.dart
lib/src/editor/block_component/table_block_component/table.dart
lib/src/editor/block_component/table_block_component/table_action.dart
lib/src/editor/block_component/table_block_component/table_block_component.dart
lib/src/editor/block_component/table_block_component/table_col.dart
lib/src/editor/block_component/table_block_component/table_col_border.dart
lib/src/editor/block_component/table_block_component/table_view.dart
lib/src/editor/editor_component/service/shortcuts/character/slash_command.dart
lib/src/plugins/html/html_document_decoder.dart
lib/src/plugins/markdown/decoder/parser/markdown_table_parser.dart
pubspec.yaml
test/new/block_component/table_block_component/table_action_test.dart
test/new/block_component/table_block_component/table_block_component_test.dart
test/new/block_component/table_block_component/table_commands_test.dart
test/new/block_component/table_block_component/table_view_test.dart
test/new/infra/testable_editor.dart
test/plugins/html/encoder/parser/table_node_parser_test.dart
test/service/selection_service_test.dart

- sort the dependencies
- expose table API

feat: optimize table update

---

lib/src/editor/editor_component/service/ime/non_delta_input_service.dart

Closed https://github.com/AppFlowy-IO/AppFlowy/issues/6165
@LucasXu0 View records found to be handwritten input method can not input the solution to the problem deleted
I did not find this problem in the macos test, please inform me of the reason for deletion

fix:chinese input

---

lib/src/editor/block_component/table_block_component/table_block_component.dart
lib/src/editor/block_component/table_block_component/table_cell_block_component.dart
lib/src/editor/block_component/table_block_component/table_node.dart
test/new/block_component/table_block_component/table_node_test.dart

Remove the assertion and forced unwrapping, make the code more production-friendly, and add more logging.

feat: optimize the table node parse steps and add logs

---

.github/workflows/test.yml
lib/src/editor/toolbar/desktop/items/link/link_menu.dart
lib/src/editor/toolbar/desktop/items/link/link_toolbar_item.dart
lib/src/editor/util/link_util.dart

According to https://github.com/AppFlowy-IO/AppFlowy/issues/5146 I added support of `mailto` and `file` URIs.
It's also possible to use built-in [Uri.tryParse](https://api.flutter.dev/flutter/dart-core/Uri/tryParse.html) to support any URI, but I'm not sure if this is a good idea since it allows any schema (e.g. `javascript` too) and probably should be validated more. 
So for now I left it simple.

feat: support more link types

---

lib/src/editor/editor_component/service/ime/delta_input_on_floating_cursor_update.dart
lib/src/editor/editor_component/service/ime/delta_input_on_replace_impl.dart
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/util/platform_extension.dart

Solves:
#873 
#880 
Modification of isIOS and isMacOS verification code execution on the web

fix: unsupported platform error on web

---

lib/src/core/document/document.dart
test/core/document/document_test.dart

fix issue https://github.com/AppFlowy-IO/appflowy-editor/issues/884

fix: document getting first or last node exception

---

example/lib/home_page.dart
example/lib/main.dart
example/lib/pages/desktop_editor.dart
example/lib/pages/drag_to_reorder_editor.dart
example/pubspec.yaml
lib/src/core/document/node.dart
lib/src/editor/block_component/base_component/block_component_action_wrapper.dart
lib/src/editor/block_component/base_component/block_component_configuration.dart
lib/src/editor/editor_component/service/renderer/block_component_container.dart
lib/src/editor/editor_component/service/renderer/block_component_service.dart
lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
lib/src/editor/editor_component/service/selection_service.dart

https://github.com/user-attachments/assets/1787bdca-ade0-4ae8-afdb-504a975553d1

feat: support dragging to reorder block

---

lib/src/editor/editor_component/service/ime/delta_input_on_insert_impl.dart
lib/src/editor/editor_component/service/ime/delta_input_on_non_text_update_impl.dart
lib/src/editor/editor_component/service/keyboard_service_widget.dart
test/editor/editor_component/ime/delta_input_on_non_text_update_impl_test.dart

'`' in the French IME can trigger a character style convention. It can't be parsed as inline code in this case.
closes https://github.com/AppFlowy-IO/AppFlowy/issues/5299

fix: backquote key will cause crash when using Frence IME

---

lib/src/editor/toolbar/mobile/mobile_floating_toolbar/mobile_floating_toolbar.dart

fix: context menu doesn't show up when the first paragraph is empty

---

lib/src/editor/editor_component/service/editor.dart
lib/src/editor/editor_component/service/scroll_service_widget.dart
lib/src/editor_state.dart

When using the `MobileFloatingToolbar` with a markdown editor not in full screen design (e.g. if a docked footer is present on the screen), the default auto scroll edge might not work and would lead to the following assertion error:
```
assert(
globalRect.size.width >= _dragTargetRelatedToScrollOrigin.size.width &&
globalRect.size.height >=
_dragTargetRelatedToScrollOrigin.size.height,
'Drag target size is larger than scrollable size, which may cause bouncing',
);
```
In this case it might be useful to allow configuring the edge offset.

feat: Allow configuring the auto scroll edge offset

---

example/lib/pages/drag_to_reorder_editor.dart
lib/src/core/document/path.dart
lib/src/core/transform/operation.dart
lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
lib/src/editor/editor_component/service/selection_service.dart
lib/src/editor/editor_component/service/selection_service_widget.dart
test/core/document/path_test.dart

Expose the `builder` parameters in `renderDropTargetForOffset` function to allow developers to customize the drag area widget.
https://github.com/user-attachments/assets/2ee8de7d-ffe3-48c1-9cc3-3248d78b3ed8

feat: support moving a block to become a child of another block

---

.github/workflows/test.yml
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/editor_component/service/keyboard_service_widget.dart

In some cases, the `onDelete` command doesn't trigger as expected, but at that time, Flutter will call `performSelector` instead.

feat: listen on delete_backward changes

---

example/lib/pages/editor.dart
lib/src/core/location/selection.dart
lib/src/editor/editor_component/service/ime/delta_input_on_non_text_update_impl.dart
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/editor_component/service/shortcuts/character/format_single_character/format_single_character.dart

Before that, we only supported formatting text when the selection was collapsed and the composing range was collapsed. 
For some IMEs, especially those combining backtick with other characters to input a new character, the composing range is not collapsed before formatting text. 
Solution: Check if the newly input character is formattable, even if the composing range is not collapsed. If so, format it; otherwise, ignore it.
https://github.com/user-attachments/assets/84c0aa44-b59d-4693-8df7-2d0ed39a475a

feat: support formatting text when the composing range is not collapsed

---

lib/src/core/transform/transaction.dart
lib/src/editor/editor_component/service/ime/delta_input_on_insert_impl.dart
lib/src/editor_state.dart
test/customer/slice_attributes_test.dart

Skip formatting for continued input after space key press
Example:
`**Hello**` + press space key +  `World` will become **Hello**  World
``**Hello**`` + press space key + press backspace key + `World` will become **HelloWorld**

feat: support skipping slice attributes

---

lib/src/editor/editor_component/service/keyboard_service.dart
lib/src/editor/editor_component/service/keyboard_service_widget.dart

Provide a keyboard service interceptor to allow developers to override or inject built-in keyboard operations.
```dart
abstract class AppFlowyKeyboardServiceInterceptor {
/// Intercept insert operation
Future<bool> interceptInsert(
TextEditingDeltaInsertion insertion,
EditorState editorState,
List<CharacterShortcutEvent> characterShortcutEvents,
) async {
return false;
}
/// Intercept delete operation
Future<bool> interceptDelete(
TextEditingDeltaDeletion deletion,
EditorState editorState,
) async {
return false;
}
/// Intercept replace operation
Future<bool> interceptReplace(
TextEditingDeltaReplacement replacement,
EditorState editorState,
List<CharacterShortcutEvent> characterShortcutEvents,
) async {
return false;
}
/// Intercept non-text update operation
Future<bool> …
```

feat: add keyboard service interceptor to prevent default ops execution

---

lib/src/editor/editor_component/service/ime/delta_input_on_floating_cursor_update.dart
lib/src/editor/editor_component/service/ime/delta_input_on_non_text_update_impl.dart
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/editor_component/service/selection/mobile_selection_service.dart

https://github.com/user-attachments/assets/dca8bb6b-e02f-420a-a23b-d08bdc5d1891
https://github.com/user-attachments/assets/fcd29e94-9960-460a-8991-a3e68d99c8a9

feat: support keyboard gesture on mobile

---

lib/src/editor/block_component/base_component/delete_line_command.dart
lib/src/editor/block_component/block_component.dart
lib/src/editor/block_component/standard_block_components.dart
test/new/service/shortcuts/command_shortcut_events/delete_line_command_test.dart

Press Cmd (on Mac) or Ctrl (on Windows/Linux) + X will:
related to https://github.com/AppFlowy-IO/AppFlowy/issues/6425

feat: add 'delete line' command shortcut

---

lib/src/editor/editor_component/service/shortcuts/command/copy_paste_extension.dart
test/new/editor_component/service/shortcuts/command_shortcuts/paste_command_test.dart

closes https://github.com/AppFlowy-IO/AppFlowy/issues/6440
If the pasted content starts with a non-delta block, insert the content below the current selection. Otherwise, keep the original logic.

fix: insert the pasted nodes after current selection if they start with a non-delta node

---

lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
lib/src/service/selection/selection_gesture.dart

By default, the `panStart` callback from `PanGestureRecognizer` won't be triggered immediately after dragging starts. It will be delayed, causing the start offset point to not match the real offset point on the screen. For example, when you start dragging from offset(0,0) horizontally, the panStart callback may trigger at offset(2, 0), which causes the start selection calculation to be incorrect.
The solution is to implement a custom `PanGesture` which triggers the `panStart` call immediately without any delay.
https://github.com/user-attachments/assets/c9344c58-c17f-4f91-be24-267760025ea9

feat: implement custom pan gesture to avoid delay offset update

---

lib/src/core/document/text_delta.dart
test/customer/slice_attributes_test.dart

1. Slice attributes from the next position only if the cursor index is **0**.
2. Slice attributes from the previous position if the cursor is **not 0.**
https://github.com/user-attachments/assets/68ba9833-7706-43cf-8e01-ad24389bd60b

feat: slice attribute from next position if index is 0

---

lib/src/editor/editor_component/service/selection/desktop_selection_service.dart

Just a minor thing I noticed, if I have an empty node and I'm dragging horizontally, I could see the cursor blinking fast as if the selection updates all the time, but we shouldn't notify about the update unless the selection actually did change.

fix: only notify ui of selection change if it actually changed

---

lib/src/editor/toolbar/desktop/items/color/highlight_color_toolbar_item.dart
lib/src/editor/toolbar/desktop/items/color/text_color_toolbar_item.dart
lib/src/editor/toolbar/desktop/items/format_toolbar_items.dart
lib/src/render/toolbar/toolbar_item.dart

Closes: [#1681](https://github.com/AppFlowy-IO/AppFlowy/issues/1681)
This is simply an improvement to the behavior, there is nothing to "apply" formatting options on, so should we even show these options? We can improve that later..
https://github.com/user-attachments/assets/d38511a3-fe40-4979-8f69-b34a565f5c03
https://github.com/user-attachments/assets/622505e3-40dc-41b4-afe1-b8fe3d0c3b65

fix: do not highlight inactive items on empty selection

---

example/lib/home_page.dart
example/lib/pages/auto_expand_editor.dart

https://github.com/user-attachments/assets/ef2926b4-9df9-41ba-9622-847cc914a2d4
```dart
return Scaffold(
appBar: AppBar(
backgroundColor: Colors.black,
title: const Text('Custom Theme For Editor'),
titleTextStyle: const TextStyle(color: Colors.white),
iconTheme: const IconThemeData(
color: Colors.white,
),
),
body: SafeArea(
child: Center(
child: IntrinsicHeight(
child: Container(
alignment: Alignment.center,
decoration: BoxDecoration(
border: Border.all(color: Colors.grey),
),
constraints: const BoxConstraints(
maxHeight: 360,
maxWidth: 400,
),
child: SingleChildScrollView(
child: IntrinsicHeight(
child: AppFlowyEditor(
editorState: editorState,
disableAutoScroll: true,
shrinkWrap: true,
editorStyle: const EditorStyle.desktop(
padding: EdgeInsets.symmetric(horizontal: 8),
), …
```

feat: add auto expanded editor showcase

---

lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart
lib/src/editor/block_component/divider_block_component/divider_block_component.dart
lib/src/editor/block_component/heading_block_component/heading_block_component.dart
lib/src/editor/block_component/image_block_component/image_block_component.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/paragraph_block_component/paragraph_block_component.dart
lib/src/editor/block_component/quote_block_component/quote_block_component.dart
lib/src/editor/block_component/table_block_component/table_block_component.dart
lib/src/editor/block_component/table_block_component/table_cell_block_component.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
lib/src/editor/editor_component/service/renderer/block_component_service.dart
test/customer/custom_error_block_test.dart

Changed the validator to be customizable and support overriding it.
This is helpful if you want to override the existing validator.

feat: override block component validator

---

CHANGELOG.md
pubspec.yaml

- feat: support dragging to reorder block by @LucasXu0 in [#887](https://github.com/AppFlowy-IO/appflowy-editor/pull/887)
- feat: implement auto scroll when draggaing to reorder by @LucasXu0 in [#889](https://github.com/AppFlowy-IO/appflowy-editor/pull/889)
- feat: Allow configuring the auto scroll edge offset by @snipd-min in [#888](https://github.com/AppFlowy-IO/appflowy-editor/pull/888)
- feat: support moving a block to become a child of another block by @LucasXu0 in [#896](https://github.com/AppFlowy-IO/appflowy-editor/pull/896)
- feat: listen on delete_backward changes by @LucasXu0 in [#898](https://github.com/AppFlowy-IO/appflowy-editor/pull/898)
- feat: support formatting text when the composing range is not collapsed by @LucasXu0 in …

chore: bump version 4.0.0

---

lib/src/plugins/html/html_document.dart
lib/src/plugins/html/html_document_decoder.dart
test/plugins/html/html_document_test.dart

closes https://github.com/AppFlowy-IO/appflowy-editor/issues/913
Support decoding H4-H6 when parsing HTML.

fix: html decoder ignores h4-h6 tags

---

example/pubspec.yaml
lib/src/plugins/markdown/decoder/document_markdown_decoder.dart
lib/src/plugins/markdown/decoder/parser/markdown_paragraph_parser.dart
test/plugins/markdown/document_markdown_test.dart

closes https://github.com/AppFlowy-IO/appflowy-editor/issues/912

fix: markdown parser doesn't recognize softline breaks

---

example/lib/pages/desktop_editor.dart
example/lib/pages/drag_to_reorder_editor.dart
lib/src/core/document/path.dart
lib/src/editor/block_component/base_component/block_component_configuration.dart
lib/src/editor/block_component/base_component/selection/block_selection_area.dart
lib/src/editor_state.dart

Use the API below to select multiple lines with block selection style.
```dart
final selection = Selection.collapsed(
Position(path: path),
);
editorState.updateSelectionWithReason(
selection,
customSelectionType: SelectionType.block,
);
```
```dart
value.configuration = value.configuration.copyWith(
padding: (_) => const EdgeInsets.symmetric(vertical: 8.0),
blockSelectionAreaMargin: (_) => const EdgeInsets.symmetric(
vertical: 1.0,
),
);
```

feat: select multiple lines with block selection style

---

example/lib/pages/editor.dart
lib/src/core/document/text_delta.dart
lib/src/editor/editor_component/service/ime/delta_input_on_non_text_update_impl.dart
lib/src/editor_state.dart

Allow the developer to customize the delta slice function. 
One use case is skipping formatting for inline code of the subsequently input text with French IME.

feat: custom slice function

---

lib/src/core/document/attributes.dart
lib/src/core/document/text_delta.dart
test/core/document/text_delta_test.dart

updating the same attribute should return a 'retain' operation instead of 'insert' and 'delete' operations.

fix: use retain instead of insert/delete for same attr

---

lib/src/core/transform/transaction.dart
test/core/transform/transaction_test.dart

If the last node after slicing is empty, don't combine the last replace text with it.

fix: replace texts assertion

---

lib/src/core/transform/transaction.dart
test/core/transform/transaction_test.dart

Example:
Formatting the link [AppFlowy](appflowy.io) to [AppFlowy.IO](appflowy.io) loses the href attribute if AppFlowy is at the beginning of the text.

fix: links starting with 0 index lose href attribute after formating

---

lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
lib/src/editor_state.dart

Tapping on mobile to select text should cancel the block selection.

fix: cancel block selection when tapping the editor on mobile

---

lib/src/editor/editor_component/service/scroll/editor_scroll_controller.dart
lib/src/editor/find_replace_menu/search_service_v3.dart

I think some logic got lost during the transition from v2 to v3
no tests yet, need review
regression on appflowy main repo: entering text into the find text field causes title to get focus if it's empty

fix: highlight search match not scrolling document to reveal said match

---

lib/src/editor/selection_menu/selection_menu_widget.dart

closes : https://github.com/AppFlowy-IO/AppFlowy/issues/6265
I have added the name in keywords list where the in18 keys are added so whenever any one searche in their native language and the key is availaible then it will consider the key while searching for a section.
https://github.com/user-attachments/assets/20a65eaf-5d69-4d04-999a-899ce39bcdef

fix: Searching command with / using in18

---

lib/src/service/internal_key_event_handlers/copy_paste_handler.dart

Currently, calling a cut action on a table cell will completely crash the table editor. it leaves the document in a state where a table has no cells, rather then deleting it completely.
Not sure if this approach is the best, but gets the job done. Any ideas welcome.
Warning: This won't retroactively fix editor states where the Document has already been broken prior to this patch.

fix: cut collapsed table cell won't crash the editor

---

lib/src/editor/block_component/table_block_component/table_action.dart

Dear all,
First ever pull request, probably not great, but it solves https://github.com/AppFlowy-IO/appflowy-editor/issues/948 , by preventing an empty state Document that bricks the editor after deleting a table, when such table was the last thing on the Document, leaving the editor in an broken state.
In my app, since users bricked their save games with this bug, I am detecting (after loading from file), whether there is any Document on empty state, and if so, I overwrite them with a blank Document. This is to recover into a healthy state, with this patch preventing it from happening again (from this, or any other cause that leads to the same state).
Any suggestions welcome, it just gets the work done for now.
Best regards
Saif

fix: deleting the last table being the last node of the document, places an empty node to avoid the editor to crash

---

lib/src/editor/editor_component/service/shortcuts/command/paste_command.dart
lib/src/service/internal_key_event_handlers/copy_paste_handler.dart
test/new/editor_component/service/shortcuts/command_shortcuts/paste_command_test.dart

This PR addresses **Issue #957**, ensuring that phone numbers are detected, highlighted, and functional within the AppFlowy Editor. The issue has been resolved, and this PR closes it.
---
- **Phone Number Detection**: Phone numbers are now automatically detected and highlighted, following the same style as URLs.
- **Interactive Features**:
- On mobile devices, tapping a phone number allows users to:
- Call the number.
- Save it to their contacts directory.
- **Non-Intrusive Changes**:
- Existing functionalities for URLs and emails remain unaffected.
- All code follows established formatting guidelines and includes comments for clarity.
---
- **Test Results**:
- All existing and new test cases pass successfully.
- Comprehensive manual testing was conducted to verify functionality across …

fix: editor now detects phone number and launches it

---

lib/src/editor/editor_component/service/ime/delta_input_on_delete_impl.dart

Pressing "delete" (aka Backspace) on Android crashes the editor when called inside the empty cell of a table. It leaves the table in an invalid state, crashing the Editor.
This fix or workaround ignores backspaces called inside table cells at the first offset position of the cursor.
Any suggestions welcome!

fix: ignore backspace on empty table cells to avoid editor crash

---

example/pubspec.yaml
lib/src/editor/editor_component/service/ime/delta_input_on_delete_impl.dart
lib/src/editor/toolbar/desktop/floating_toolbar.dart
test/new/toolbar/desktop/floating_toolbar_test.dart

Hide the floating toolbar if no content is visible.

fix: hide the floating toolbar if no content is visible

---

lib/src/editor/editor_component/service/shortcuts/character/slash_command.dart
lib/src/editor/selection_menu/selection_menu_service.dart
lib/src/editor/selection_menu/selection_menu_widget.dart

closes https://github.com/AppFlowy-IO/AppFlowy/issues/6865
Add a new parameter to enable deletion of keywords before inserting the new block.

fix: creating document from slash menu leaves text behind

---

lib/src/editor/editor_component/service/shortcuts/character/slash_command.dart

Use `supportSlashMenuNodeTypes` to customize which nodes support the slash menu.
```
CharacterShortcutEvent customSlashCommand(
List<SelectionMenuItem> items, {
// ...
Set<String> supportSlashMenuNodeTypes = _defaultSupportSlashMenuNodeTypes,
})
```

feat: support customize supported node types for slash menu

---

lib/src/editor/toolbar/mobile/mobile_toolbar_v2.dart

On mobile (android) when some users open keyboard it is automatically closing.

Fixed menu closing on some devices

---

example/lib/pages/editor.dart
lib/src/core/document/text_delta.dart
test/customer/slice_attributes_test.dart

Reset to the default inline code format: only format the inline code if the input text is in inline code format.
https://github.com/user-attachments/assets/d1725b8b-7a02-4523-bf34-0b1bf003269a

feat: reset to the default inline code format logic

---

lib/src/core/document/text_delta.dart
lib/src/editor/block_component/rich_text/appflowy_rich_text_keys.dart

Add the `partialSliced` value to indicate whether the key should be sliced if the index is out of the attribute's range.
For example, if you only need to slice the attributes when the index is within the attribute's range, add the key to partialSliced.
`**Hello World**` <- If you input here, it should not follow the previous format if the `partialSliced` value contains the `AppFlowyRichTextKeys.bold`

feat: add `partialSliced` to support partial sliced attributes

---

lib/src/editor/block_component/base_component/insert_newline_in_type_command.dart
lib/src/editor/editor_component/service/ime/character_shortcut_event_helper.dart
lib/src/editor/editor_component/service/shortcuts/command/backspace_command.dart
lib/src/editor/editor_component/service/shortcuts/command/select_all_command.dart
test/editor/block_component/base_component/insert_newline_in_type_command_test.dart

Ignore the shift+enter in insertNewLine shortcut and let the system handle it.

fix: shift+enter should wrap the line in list

---

lib/src/plugins/html/html_document_decoder.dart
test/plugins/html/html_document_test.dart

Complete the logic to fix issue https://github.com/AppFlowy-IO/AppFlowy/issues/6808
https://github.com/user-attachments/assets/38915b96-686d-4397-be98-f6fd102a27ce

fix: all the text pasted from google doc will be applied inline link

---

lib/src/editor/editor_component/service/ime/text_diff.dart
test/editor/editor_component/ime/text_diff_test.dart

To fix #981
Before: 
https://github.com/user-attachments/assets/2c097d3f-142d-4c66-b531-b003194e94de
After:
https://github.com/user-attachments/assets/4a47f02a-d5be-4878-9c8f-280b67db83f0

fix: sougou IME issue on Windows

---

lib/src/core/document/node.dart

Add a `deepCopy` function to improve the readability of the original `copyWith` function.

feat: deep copy the node

---

lib/src/editor/editor_component/service/selection/mobile_selection_service.dart

fix: checking is mounted before updating the value of PropertyValueNotifier(#977)

---

lib/src/editor/block_component/base_component/block_component_configuration.dart
lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart
lib/src/editor/block_component/heading_block_component/heading_block_component.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/paragraph_block_component/paragraph_block_component.dart
lib/src/editor/block_component/quote_block_component/quote_block_component.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart

added support for customizing the text alignment for each block.
```dart
/// The text align of a block component.
///
/// This value is only available for the block with text,
/// e.g. paragraph, heading, quote, to-do list, bulleted list, numbered list
final TextAlign Function(Node node) textAlign;
```

feat: support text align in text-based blocks

---

example/lib/pages/mobile_editor.dart
lib/src/core/transform/transaction.dart
lib/src/editor/editor_component/service/ime/delta_input_on_non_text_update_impl.dart
lib/src/editor/editor_component/service/ime/delta_input_service.dart
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/editor_component/service/ime/text_input_service.dart
lib/src/editor/editor_component/service/keyboard_service_widget.dart
lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
lib/src/editor/editor_component/style/editor_style.dart
lib/src/editor_state.dart
lib/src/render/selection/mobile_basic_handle.dart
lib/src/render/selection/mobile_collapsed_handle.dart

Set `editorState.debugInfo.debugPaintSizeEnabled` to true to render the paint size for the mobile drag handle.

feat: enable debug paint size for mobile drag handle

---

lib/src/editor/editor_component/service/ime/non_delta_input_service.dart

Problem:
https://github.com/user-attachments/assets/73f25a31-b82a-495b-9578-d8f638bd3ae7
Re-positioning the cursor in the middle of sentence while composing occurs following error. 
so I add logic for checking validity of cursor position.

fix: out of text range while composing error

---

lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
test/editor/editor_component/ime/non_delta_input_service_test.dart

To fix https://github.com/AppFlowy-IO/AppFlowy/issues/7049
Before the fix: 
https://github.com/user-attachments/assets/20455a8e-2303-4394-9e52-70d696a01bc4
After the fix:
https://github.com/user-attachments/assets/a89a7e7f-c250-4729-9aba-091ea50f2811

fix: error format of TextEditingDeltaInsertion

---

lib/src/editor/editor_component/service/ime/character_shortcut_event_helper.dart
test/editor/editor_component/ime/character_shortcut_on_insert_impl_test.dart

The keyboard inserts ' \n' instead of '\n' when pressing Enter after an emoji. We should ignore the space in this case.

fix: enter after emoji will create a softbreak on mobile

---

example/lib/pages/customize_theme_for_editor.dart
lib/src/editor/block_component/base_component/block_component_configuration.dart
lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart
lib/src/editor/block_component/heading_block_component/heading_block_component.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/paragraph_block_component/paragraph_block_component.dart
lib/src/editor/block_component/quote_block_component/quote_block_component.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
lib/src/editor/selection_menu/selection_menu_service.dart
lib/src/editor_state.dart

Expose the TextSpan for the TextStyle builder. In most use cases, the TextStyle in TextSpan can be used as a base to customize additional styles.

feat: expose text span for text style builder

---

lib/src/editor/editor_component/service/ime/delta_input_on_non_text_update_impl.dart

the `selection != editorState.selection` will always be `false`
remove it then the space bar is able to work correctly

fix: using space bar to move the cursor not working on Android

---

example/pubspec.yaml
lib/src/editor/editor_component/service/ime/delta_input_on_non_text_update_impl.dart
lib/src/plugins/markdown/decoder/document_markdown_decoder.dart
lib/src/plugins/markdown/decoder/parser/markdown_image_parser.dart
lib/src/plugins/markdown/decoder/parser/markdown_paragraph_parser.dart
test/plugins/markdown/document_markdown_test.dart

Parse the image without a line break or single link break after the text.

fix: unable to parse image if the image is inside the paragraph

---

lib/src/editor/editor_component/service/scroll_service_widget.dart

cases to consider that I don't know the best solution to:
- whether to replace existing logic with the new one and not check for the cursor rect
- when using shrinkWrap, the `ItemScrollableController` isn't available

fix: use jump to when cursor not rendered

---

lib/src/editor/block_component/base_component/block_component_configuration.dart

To fix [#7153](https://github.com/AppFlowy-IO/AppFlowy/issues/7153)
Before the fix:
https://github.com/user-attachments/assets/987ab270-1758-44d9-813f-41c6b67bd9c8
After the fix:
https://github.com/user-attachments/assets/33b74dc4-db61-4320-b9cc-5fab508376e6

fix: RTL languages display incorrectly with soft line break(#7153)

---

lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
lib/src/editor/editor_component/service/selection/mobile_selection_service.dart
lib/src/editor/editor_component/service/selection_service.dart
lib/src/editor/editor_component/service/selection_service_widget.dart

Use the `DragTargetNodeInterceptor` function to intercept the drag target node in certain scenarios.
For example, if two hit tests are exclusiv. Let's say a column block contains multiple paragraphs inside it, if the developers want to drag another paragraph to the right side of the paragraphs in the column block to create a new column after the current one, they can use the function to replace the default target node, which is the paragraph node, with the new column node.

feat: add interceptor into selection service to custom the drag target node

---

lib/src/flutter/scrollable_positioned_list/src/scrollable_positioned_list.dart

fix the error:
```
A ScrollController was used after being disposed.
Once you have called dispose() on a ScrollController, it can no longer be used.
When the exception was thrown, this was the stack:
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:183:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:190:6)
#2      ChangeNotifier.dispose (package:flutter/src/foundation/change_notifier.dart:379:27)
#3      ScrollController.dispose (package:flutter/src/widgets/scroll_controller.dart:267:11)
#4      _ScrollablePositionedListState.dispose (package:appflowy_editor/src/flutter/scrollable_positioned_list/src/scrollable_positioned_list.dart:385:32)
...
```

fix: scrollController disposed twice

---

lib/src/editor/block_component/base_component/block_component_action_wrapper.dart
lib/src/editor/block_component/base_component/selection/block_selection_container.dart
lib/src/editor/block_component/base_component/widget/nested_list_widget.dart
lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart
lib/src/editor/block_component/divider_block_component/divider_block_component.dart
lib/src/editor/block_component/heading_block_component/heading_block_component.dart
lib/src/editor/block_component/image_block_component/image_block_component.dart
lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
lib/src/editor/block_component/paragraph_block_component/paragraph_block_component.dart
lib/src/editor/block_component/quote_block_component/quote_block_component.dart
lib/src/editor/block_component/table_block_component/table_block_component.dart
lib/src/editor/block_component/table_block_component/table_cell_block_component.dart
lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
lib/src/editor/editor_component/entry/page_block_component.dart
lib/src/editor/editor_component/service/renderer/block_component_service.dart
lib/src/editor/editor_component/service/renderer/block_component_widget.dart
lib/src/plugins/blocks/columns/column_block_component.dart
lib/src/plugins/blocks/columns/columns_block_component.dart
test/customer/custom_error_block_test.dart

- Customize the selection area position. We can use the position to control the selection area either above or below the block.
- Add a trailing builder in the block menu. We can use it to add more padding between the block and the block menu.
---
The red box in the screenshot is added by the trailing builder to ensure that the block menu doesn't overlap with the blue quote icon.

feat: add trailing builder in block menu

---

lib/src/editor_state.dart

In order to expose the `onScrollViewScrolled` listener to the outside

chore: add ScrollViewScrolledListener to EditorState

---

lib/src/editor/selection_menu/selection_menu_service.dart

fix: menu position error

---

lib/src/editor/editor_component/service/ime/delta_input_service.dart
lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
lib/src/editor/editor_component/service/ime/text_input_service.dart
lib/src/editor/editor_component/service/keyboard_service_widget.dart
test/editor/editor_component/ime/non_delta_input_service_test.dart

Related to a mobile slash menu issue:
**ｗhen I type ‘/’ and enter the second-level menu by selecting any item, I can return to the first-level menu using backspace. 
but after selecting items for three times, backspace no longer works to return to the first level.**

fix: interceptor not working with continuous deleting

---

example/assets/example.json
lib/src/editor/block_component/table_block_component/table_cell_block_component.dart
lib/src/editor/block_component/table_block_component/table_col.dart
lib/src/editor/block_component/table_block_component/util.dart

Add dynamic value to double conversion to ensure the width and height values from the table node are doubles.

fix: parse table width/height error if the value is int

---

lib/src/editor/editor_component/service/shortcuts/command/backspace_command.dart

Dear all,
I have noticed that in Desktop versions, if you select all (CTRL+A) and press backspace, the editor enters in a locked state. It makes it further unclickable since the document loses all node children.
This PR fixes this.
Best regards,
Saif

fix: prevent lock after backspacing on select all

---

lib/src/editor/block_component/heading_block_component/heading_command_shortcut.dart
lib/src/l10n/l10n.dart

To fix https://github.com/AppFlowy-IO/AppFlowy/issues/7586
Rename the shortcuts description to avoid misunderstanding

fix: rename the descroption of turning into heading shortcuts

---

lib/src/editor/selection_menu/selection_menu_service.dart

Enable settting menu size for SelectionMenu to correct the menu position

fix: slash menu sometimes incorrectly show on left side

---

lib/src/editor/editor_component/service/shortcuts/command/backspace_command.dart
lib/src/flutter/overlay.dart
lib/src/flutter/scrollable_helpers.dart
lib/src/flutter/scrollable_positioned_list/src/element_registry.dart
lib/src/flutter/scrollable_positioned_list/src/item_positions_listener.dart
lib/src/flutter/scrollable_positioned_list/src/item_positions_notifier.dart
lib/src/flutter/scrollable_positioned_list/src/positioned_list.dart
lib/src/flutter/scrollable_positioned_list/src/post_mount_callback.dart
lib/src/flutter/scrollable_positioned_list/src/scroll_offset_listener.dart
lib/src/flutter/scrollable_positioned_list/src/scroll_offset_notifier.dart
lib/src/flutter/scrollable_positioned_list/src/scroll_view.dart
lib/src/flutter/scrollable_positioned_list/src/scrollable_positioned_list.dart
lib/src/flutter/scrollable_positioned_list/src/viewport.dart
lib/src/flutter/scrollable_positioned_list/src/wrapping.dart
test/new/service/shortcuts/command_shortcut_events/backspace_command_test.dart

- After inserting the new node when deleting all nodes, we should update selection to retain cursor and focus.
- Added test to ensure it keeps working
- Ignore imported files from Flutter in coverage, seems irrelevant

fix: backspace select all

---

lib/src/editor/editor_component/service/keyboard_service_widget.dart

Fixes #1125
Fixed by providing the relevant `viewId` to `TextInputConfiguration` in `KeyboardServiceWidget`.

fix: unable to input text on windows desktop
