lib/src/core/transform/operation.dart, lib/src/service/editor_service.dart, lib/src/service/selection_service.dart, test/infra/test_editor.dart, test/render/rich_text/toolbar_rich_text_test.dart, test/service/editor_service_test.dart
=> feat: shrinkWrap option for AppFlowyEditor

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
=> chore: migrate issue templates from appflowy

lib/src/editor_state.dart, lib/src/infra/html_converter.dart, lib/src/render/image/image_upload_widget.dart, lib/src/render/style/plugin_styles.dart, test/infra/html_converter_test.dart, test/infra/test_editor.dart, test/render/image/image_upload_widget_test.dart, test/render/selection_menu/selection_menu_widget_test.dart, test/render/style/editor_style_test.dart, test/render/style/plugin_styles_test.dart
=> test: improve coverage

lib/src/render/toolbar/toolbar_item.dart
=> fix: one overlay entry for selection menu

lib/src/plugins/markdown/encoder/parser/text_node_parser.dart, test/plugins/markdown/decoder/document_markdown_decoder_test.dart, test/plugins/markdown/encoder/parser/text_node_parser_test.dart
=> fix: nested text node parser

lib/src/render/style/editor_style.dart
Wanted to use a smaller spacing between paragraphs similar to apple notes, notion etc and I believe this change is required for that.
=> Allow textPadding customization

lib/src/plugins/html/html_document_decoder.dart, pubspec.yaml, test/plugins/html/decoder/document_html_decoder_test.dart, test/plugins/html/html_document_test.dart
#139 
need help in finding that repeating text is already added or not that add attribute on that text
current progress
```
<p>&nbsp;</p>
<h1><span style="text-decoration: underline;"><em>AppFlowy</em></span> <em><strong>Editor</strong></em> is a <strong><em>highly</em> customizable</strong> <em>rich-text editor</em> for&nbsp; <em><strong>Flutter</strong></em></h1>
<ol>
<li>You <em>can</em> <strong>also</strong> use <span style="background-color: rgba(0, 188, 240, 96); font-weight: bold; font-style: italic;">AppFlowy Editor</span> as a component to build your own app.</li>
<li>ertteterttet</li>
<li>If you have questions or <strong>feedback</strong>, please submit an issue on Github or join the community along with 1000+ builders!</li>
</ol>
<ul> …
```
=> fix:html to node converter fixes

lib/src/editor/toolbar/items/format_toolbar_items.dart
=> fix: fixed toolbar item tooltip desciption for embed code button

lib/src/service/editor_service.dart
closes https://github.com/AppFlowy-IO/appflowy-editor/issues/180
=> chore: mark selectionMenuItems as deprecated

lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/2819
=> fix: numbered lists have issue with the dot

lib/src/editor/editor_component/service/selection/desktop_selection_service.dart, test/new/service/shortcuts/command_shortcut_events/backspace_command_test.dart
=> fix: unable to delete the divider via backspace

example/lib/plugin/AI/auto_completion.dart, example/lib/plugin/AI/continue_to_write.dart, lib/src/editor/block_component/divider_block_component/divider_character_shortcut.dart, lib/src/editor/editor_component/service/shortcuts/character_shortcut_event.dart, lib/src/service/standard_block_components.dart, test/new/block_component/divider_block_component/divider_character_shortcut_test.dart, test/new/service/shortcuts/character_shortcut_events/character_shortcut_event_test.dart
- User can now add divider using underscore (_) shortcut
Fixes: https://github.com/AppFlowy-IO/AppFlowy/issues/2372
=> [feat] Add underline shortcut

lib/src/editor/editor_component/service/keyboard_service_widget.dart, lib/src/editor/editor_component/service/scroll/auto_scrollable_widget.dart, test/customer/text_field_and_editor_test.dart
=> fix: focus node doesn't work on mobile

lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
=> feat: support mobile IME

lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_down_command.dart, lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/arrow_up_command.dart, test/new/service/shortcuts/command_shortcut_events/delete_command_test.dart
This PR also aims at solving two of the TODOs related to renaming commands.
=> test: for testing parent child delete case

lib/src/editor/editor_component/service/keyboard_service_widget.dart, lib/src/editor/editor_component/service/shortcuts/character_shortcut_events/slash_command.dart
=> fix: unable to access the slash menu on web platform

CHANGELOG.md, documentation/UPGRADING.md, lib/l10n/intl_en.arb, lib/src/l10n/intl/messages_en.dart, lib/src/l10n/l10n.dart, pubspec.yaml
_If you are upgrading: please see [`UPGRADING.md`](https://github.com/AppFlowy-IO/appflowy-editor/blob/main/documentation/migration.md)._
* feat: added support for RTL and AUTO direction by @zoli in ([#191](https://github.com/AppFlowy-IO/appflowy-editor/pull/191))
* feat: added support for customizing href behavior by @LucasXu0 in ([#293](https://github.com/AppFlowy-IO/appflowy-editor/pull/293))
* feat: added support for delete key shortcut by @MayurSMahajan in ([#272](https://github.com/AppFlowy-IO/appflowy-editor/pull/272))
* feat: added support customize the font family by @LucasXu0 in ([#300](https://github.com/AppFlowy-IO/appflowy-editor/pull/300))
* fix: slash menu keyword not shows up the option by @johansutrisno in ([#268](https://github.com/AppFlowy-IO/appflowy-editor/pull/268)) …
=> chore: bump version 1.2.0

lib/src/editor/block_component/standard_block_components.dart, lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/backspace_command.dart, lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/command_shortcut_events.dart, lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/remove_word_command.dart, test/new/service/shortcuts/command_shortcut_events/remove_word_command_test.dart
Solves [#1270](https://github.com/AppFlowy-IO/AppFlowy/issues/1270)
=> feat: delete right word with ctrl+delete

lib/src/infra/clipboard.dart, lib/src/service/internal_key_event_handlers/copy_paste_handler.dart, test/new/editor_component/service/shortcuts/command_shortcuts/paste_command_test.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/3030
=> fix: unable to paste multiple lines

lib/src/editor/toolbar/desktop/items/link/link_toolbar_item.dart
Solve the problem of screen appearing at critical positions when there is a URL in the link menu
=> link menu issue

lib/src/plugins/quill_delta/quill_delta_encoder.dart, test/plugins/quill_delta/quill_delta_encoder_test.dart
=> fix: import single line delta failed

lib/src/editor/editor_component/service/ime/delta_input_on_non_text_update_impl.dart, lib/src/editor/editor_component/service/ime/non_delta_input_service.dart, lib/src/editor/editor_component/service/keyboard_service_widget.dart, lib/src/editor/util/platform_extension.dart, test/editor/editor_component/ime/delta_input_on_non_text_update_impl_test.dart
https://www.loom.com/share/60449cc32e1d4897a2b7e2f6e68e62b1
https://www.loom.com/share/292f65c1fd9240b389f881388b6bb871
=> feat: improve CJK IME support

lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/copy_command.dart, lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/copy_paste_extension.dart, lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/paste_command.dart, test/new/editor_component/service/shortcuts/command_shortcuts/paste_command_test.dart, test/new/service/shortcuts/command_shortcut_events/paste_command_test.dart
=> feat: migrate copy paste command from AppFlowy

lib/src/editor/find_replace_menu/find_replace_widget.dart, lib/src/editor/find_replace_menu/search_service.dart, test/new/find_replace_menu/find_replace_menu_replace_test.dart, test/new/find_replace_menu/find_replace_menu_utils.dart
Solves: #396 
https://github.com/AppFlowy-IO/appflowy-editor/assets/47064215/a31683ec-a10d-4a6a-b84b-6188a54c7e7e
=> fix: replace matches on the same node

lib/src/editor/block_component/image_block_component/resizable_image.dart
https://www.loom.com/share/8f74b4423cca46c992e7962507947bb5
closes https://github.com/AppFlowy-IO/appflowy-editor/issues/397
=> fix: update resizable image width calculation with minimum width constraint

example/lib/pages/customize_theme_for_editor.dart
closes https://github.com/AppFlowy-IO/appflowy-editor/issues/383
=> chore: update theme colors for editor

example/macos/Runner.xcodeproj/project.pbxproj, example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart, lib/src/editor/block_component/heading_block_component/heading_block_component.dart, lib/src/editor/block_component/numbered_list_block_component/numbered_list_block_component.dart, lib/src/editor/block_component/quote_block_component/quote_block_component.dart, lib/src/editor/block_component/rich_text/appflowy_rich_text.dart, lib/src/editor/block_component/text_block_component/text_block_component.dart, lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart, lib/src/extensions/alignment_extension.dart, lib/src/extensions/extensions.dart
closes https://github.com/AppFlowy-IO/appflowy-editor/issues/428
=> fix: refactor text alignment handling in block components

lib/src/editor/editor_component/service/scroll_service_widget.dart
simplify the logic and fix the assertion.
=> feat: simplify auto scroll behavior in ScrollServiceWidget

lib/src/editor/block_component/image_block_component/image_block_component.dart, lib/src/editor/block_component/image_block_component/image_upload_widget.dart, lib/src/editor/block_component/image_block_component/resizable_image.dart, lib/src/editor/util/file_picker/file_picker_impl.dart, pubspec.yaml
closes https://github.com/AppFlowy-IO/appflowy-editor/issues/364
=> fix: image upload on web

example/ios/Podfile, example/macos/Podfile
The Xcode 15 has been released today. 
Fix build error on iOS and macOS.
=> fix: DT_TOOLCHAIN_DIR path in Podfile for iOS and macOS

lib/src/editor/editor_component/service/ime/delta_input_on_delete_impl.dart, lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/backspace_command.dart, lib/src/editor/toolbar/mobile/toolbar_items/divider_mobile_toolbar_item.dart
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/abe53fee-1862-4e6b-8c9f-b8bc23c0d8fa
=> fix: delete the divider on mobile will raise an error

lib/src/editor/command/text_commands.dart, test/new/command/text_commands_test.dart
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/f6b4f15d-d8cb-421e-b79e-e86edd7cb1c8
=> fix: unable to clear the style by toggling twice

lib/src/editor/block_component/quote_block_component/quote_block_component.dart, lib/src/render/toolbar/toolbar_item.dart
- disable the toolbar in code block
- fix the icon of the quote so that it expands to the maximum height possible.
=> feat: disable toolbar in code block

example/lib/pages/editor.dart, lib/src/editor/block_component/base_component/selection/block_selection_area.dart
Fixes Issue : https://github.com/AppFlowy-IO/AppFlowy/issues/3480
<h1> Before </h1> 
<h1> After </h1>
=> fix: Applied Corner Radius to Block Selection Area

lib/src/editor/editor_component/service/shortcuts/command_shortcut_events/select_all_command.dart
=> fix: do not select all if selection is null

lib/src/editor/block_component/paragraph_block_component/paragraph_block_component.dart, lib/src/editor/editor_component/service/shortcuts/character_shortcut_events/format_double_characters/utils.dart
=> feat: show placeholder override for paragraph block

lib/src/editor/editor_component/entry/page_block_component.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/3930
=> fix: editor cannot scroll when editable is false

lib/src/editor/editor_component/service/ime/delta_input_on_non_text_update_impl.dart, lib/src/editor/editor_component/service/ime/non_delta_input_service.dart, lib/src/editor/editor_component/service/keyboard_service_widget.dart
Before
https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/438798e1-3cc9-42b1-bd5b-08091e92f577
After
https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/aac1613f-4101-4cda-929c-530b907a56d8
=> Fix input chinese issue

lib/src/editor/block_component/image_block_component/image_upload_widget.dart
Linked to https://github.com/AppFlowy-IO/appflowy-editor/issues/384 and https://github.com/AppFlowy-IO/appflowy-editor/issues/368
[Bug]: Active hover on upload image
https://github.com/AppFlowy-IO/appflowy-editor/assets/22239637/b4ecb343-47cf-4876-8743-7bdf21c1a126
https://github.com/AppFlowy-IO/appflowy-editor/assets/22239637/cc2d62a6-04d8-4305-94e0-a5a4d793787c
=> fix: active hover on upload image

CHANGELOG.md, pubspec.yaml
* feat: support customizing the mobile magnifier by @LucasXu0 in ([#625](https://github.com/AppFlowy-IO/appflowy-editor/pull/625))
* feat: support keep editor focus on mobile by @LucasXu0 in ([#628](https://github.com/AppFlowy-IO/appflowy-editor/pull/628))
* feat: support clicking the selection area to disable floating toolbar by @LucasXu0 in ([#632](https://github.com/AppFlowy-IO/appflowy-editor/pull/632))
* feat: adding an ability to have a link check before embedding by @johansutrisno in ([#603](https://github.com/AppFlowy-IO/appflowy-editor/pull/603))
* feat: Add markdown link syntax formatting by @jazima in ([#618](https://github.com/AppFlowy-IO/appflowy-editor/pull/618))
* feat: Table navigation using TAB key by @AnsahMohammad in …
=> chore: bump version 2.2.0

lib/src/editor/toolbar/mobile/mobile_toolbar_v2.dart, lib/src/editor/toolbar/mobile/utils/keyboard_height_observer.dart
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/2e0f39cf-c880-46e4-b45b-07cc6800c172
=> fix: unable to use slide gesture to close keyboard

lib/src/core/document/node.dart
related to https://github.com/AppFlowy-IO/AppFlowy/issues/4487
=> fix: unable to redo/undo in lists

example/lib/home_page.dart, example/lib/pages/fixed_toolbar_editor.dart
=> feat: add fixed toolbar example

lib/src/editor/block_component/rich_text/appflowy_rich_text.dart
=> fix: debugNeedsLayout assert for paragraph rendering on hot reload

lib/src/editor/block_component/base_component/text_style_configuration.dart, lib/src/editor/block_component/rich_text/appflowy_rich_text.dart, lib/src/editor_state.dart
Allow the user to customize the line height.
=> feat: support customizing line height

lib/src/plugins/markdown/decoder/document_markdown_decoder.dart, test/plugins/markdown/decoder/document_markdown_decoder_test.dart
Fixes https://github.com/AppFlowy-IO/appflowy-editor/issues/721
=> fix: markdown to document with image url having properties after extension

lib/src/editor/block_component/rich_text/appflowy_rich_text.dart
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/b3126f5c-0c0b-4c49-b16c-3588fcbd9d00
=> fix: incorrect cursor position after new line

lib/src/editor/editor_component/service/shortcuts/character/double/format_double_characters.dart, lib/src/editor/editor_component/service/shortcuts/character/format_single_character/format_single_character.dart, lib/src/editor_state.dart, test/new/editor_component/service/shortcuts/character_shortcuts/undo_markdown_test.dart
https://github.com/AppFlowy-IO/appflowy-editor/assets/42929161/e16d4062-243b-4ffb-9e62-d2899afafbac
=> feat: undo markdown style

lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
Related PR: https://github.com/AppFlowy-IO/appflowy-editor/pull/822
=> fix: handwriting ime doesn't work

example/lib/pages/markdown_editor.dart, lib/src/editor/editor_component/entry/page_block_component.dart, lib/src/editor/editor_component/service/editor.dart, lib/src/editor/editor_component/service/editor_service.dart, test/render/image/image_node_builder_test.dart
=> feat: enable selection in readonly mode

lib/src/editor/editor_component/service/renderer/block_component_widget.dart
fix https://github.com/AppFlowy-IO/AppFlowy/issues/5765
=> fix: force unwrap error

lib/src/editor/block_component/image_block_component/image_upload_widget.dart
=> fix: error in file selection

lib/appflowy_editor.dart, lib/src/editor/selection_menu/selection_menu_service.dart, test/service/format_rich_text_style_test.dart
expose `insertNodeAfterSelection` function
=> chore: expose text operation functions

lib/src/editor/editor_component/editor_component.dart, lib/src/editor/editor_component/service/shortcuts/command/copy_paste_extension.dart, lib/src/editor/editor_component/service/shortcuts/command/paste_command.dart
also, export copy paste extension so we can use it in AppFlowy.
=> feat: paste list children nodes

pubspec.yaml
fix:https://github.com/AppFlowy-IO/AppFlowy/issues/5573
=> feat:update keyboard height

lib/src/editor/editor_component/entry/page_block_component.dart, lib/src/editor/editor_component/service/shortcuts/character/slash_command.dart, lib/src/editor/selection_menu/selection_menu_service.dart
check the `keepEditorFocusNotifier` when showing slash menu
=> fix: set keepEditorFocusNotifier when showing slash menu

lib/src/editor/block_component/table_block_component/table_action.dart
The insertion of table cells should be in order.
=> fix: table cell insertion error

lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
Relates: https://github.com/AppFlowy-IO/AppFlowy/issues/6176
=> fix: context menu wrong offset

lib/src/editor/block_component/todo_list_block_component/todo_list_block_component.dart
=> chore: remove todolist validation and set checked as false by default

example/lib/pages/drag_to_reorder_editor.dart
Update the `drag_to_reorder` example code and enable auto-scroll when dragging to the edge.
https://github.com/user-attachments/assets/9dfac2e7-5dfe-4d1e-9e8a-d9a7f0bffc8e
=> feat: implement auto scroll when draggaing to reorder

lib/src/editor/editor_component/service/shortcuts/command/backspace_command.dart, lib/src/editor/editor_component/service/shortcuts/command/delete_command.dart
Closes: [#3999](https://github.com/AppFlowy-IO/AppFlowy/issues/3999)
=> fix: shift+delete

lib/src/editor/editor_component/service/shortcuts/command/remove_word_command.dart
Closes: [#3989](https://github.com/AppFlowy-IO/AppFlowy/issues/3989)
=> fix: ctrl+delete does not delete newlines

lib/src/plugins/pdf/html_to_pdf_encoder.dart
fix issue: https://github.com/AppFlowy-IO/appflowy-editor/issues/922
=> fix: export pdf set font not work

lib/src/editor/editor_component/service/ime/non_delta_input_service.dart
=> fix: _deleteBackward deleteRange start must > 0

pubspec.yaml
closes https://github.com/AppFlowy-IO/appflowy-editor/issues/926
=> chore: update device_info_plus to 11.0.0

lib/src/editor/block_component/rich_text/appflowy_rich_text.dart, test/new/block_component/table_block_component/table_view_test.dart
https://github.com/user-attachments/assets/26e81780-cb3a-4056-99a9-759d48e1c0b3
https://github.com/user-attachments/assets/b55b1674-fccc-434c-80fb-aad35793029e
=> fix: cursor height is inconsistent when the font size is smaller than the default text size

lib/src/extensions/node_extensions.dart, test/new/extensions/node_extension_test.dart
closes https://github.com/AppFlowy-IO/AppFlowy/issues/6807
=> fix: cross blocks format not reflected on the float toolbar

lib/src/editor/editor_component/service/shortcuts/command/paste_command.dart, lib/src/plugins/html/html_document_decoder.dart, test/plugins/html/decoder/_samples.dart, test/plugins/html/decoder/document_html_decoder_test.dart
Fix issue [#6808](https://github.com/AppFlowy-IO/AppFlowy/issues/6808)
Before the fix : 
https://github.com/user-attachments/assets/4a5ea0e4-d7d9-4032-9324-79c204776f71
After the fix:
https://github.com/user-attachments/assets/9f87cba6-c37b-47a0-8019-09a6f4dce27b
=> fix: issue #6808 of appflowy

lib/src/editor/editor_component/service/shortcuts/command/backspace_command.dart, test/new/service/shortcuts/command_shortcut_events/backspace_command_test.dart
=> fix: cross column deletion in the table

lib/src/editor/editor_component/service/scroll_service_widget.dart
testing, please don't merge yet
=> fix: check if scroll service is disposed before scrolling

lib/src/editor/editor_component/service/ime/delta_input_on_non_text_update_impl.dart
Avoid redundant updates with the same value
=> fix: the cursor constantly blinking on Android

.github/workflows/test.yml, lib/src/editor/block_component/base_component/widget/ignore_parent_gesture.dart, lib/src/editor/toolbar/desktop/floating_toolbar.dart, lib/src/editor_state.dart
- don't show the floating toolbar if the editable flag is false
- ddd editable notifier
=> feat: disable floating toolbar when editable is false

.github/workflows/test.yml, example/lib/pages/desktop_editor.dart, lib/src/editor/editor_component/service/scroll/editor_scroll_controller.dart, lib/src/editor/editor_component/service/scroll_service_widget.dart, lib/src/editor/editor_component/service/selection/desktop_selection_service.dart, lib/src/editor_state.dart
check the nodes length before updating the selection.
=> fix: editor will crash if deleting all nodes

example/lib/pages/desktop_editor.dart, example/lib/pages/drag_to_reorder_editor.dart, lib/src/editor/editor_component/service/selection/shared.dart, lib/src/plugins/blocks/columns/column_block_component.dart, lib/src/plugins/blocks/columns/column_width_resizer.dart, lib/src/plugins/blocks/columns/columns_block_component.dart, lib/src/plugins/blocks/columns/columns_block_constant.dart, lib/src/plugins/plugins.dart
Introduce the column layout and fix the issue where the selection doesn't work when the blocks are laid out horizontally.
=> feat: add simple columns block in editor

lib/src/editor/util/link_util.dart, test/render/toolbar/toolbar_link_item_test.dart
To fix [#7332](https://github.com/AppFlowy-IO/AppFlowy/issues/7332)
=> fix: support custom non-standard urls

lib/src/editor/block_component/rich_text/appflowy_rich_text.dart
To fix [#6500](https://github.com/AppFlowy-IO/AppFlowy/issues/6500)
https://github.com/user-attachments/assets/455fc8bc-ad04-4fec-97a4-17014b99d88a
=> fix: add default selection area for empty character

lib/src/editor/editor_component/service/shortcuts/command/open_link_command.dart, lib/src/editor/editor_component/style/default_text_span_decorator_for_attribute.dart, lib/src/editor/toolbar/desktop/items/link/link_toolbar_item.dart, lib/src/extensions/url_launcher_extension.dart, test/extensions/url_launcher_extension_test.dart, test/mobile/editor/editor_component/style/mobile_text_span_decorator_for_attribute_test.dart
support customizing the link actions in the toolbar
=> feat: support customizing link button

lib/src/editor/editor_component/service/keyboard_service.dart, lib/src/editor/editor_component/service/keyboard_service_widget.dart
```
/// Enable the keyboard shortcuts
void enableShortcuts();
/// Disable the keyboard shortcuts
void disableShortcuts();
```
Call these two functions to disable shortcuts. Note that you must call `enableShortcuts` once you no longer need to disable shortcuts. Otherwise, the keyboard shortcuts will no longer work.
=> feat: add flag to disable keyboard shortcuts

lib/src/flutter/scrollable_helpers.dart
Remove the logic that returns the auto-scroll earlier. The scroll size will be recalculated in the code below.
=> fix: auto scroll issue

example/lib/pages/editor_list.dart, lib/src/editor/editor_component/service/editor.dart
- Fixed the assertion in editor list example
- Update the comment of the editable field in AppFlowyEditor
closes https://github.com/AppFlowy-IO/appflowy-editor/issues/1060
closes https://github.com/AppFlowy-IO/appflowy-editor/issues/1059
=> fix: assertion in editor list example

lib/src/editor/editor_component/service/keyboard_service_widget.dart, lib/src/editor/editor_component/service/shortcuts/command/undo_redo_command.dart, test/new/service/shortcuts/command_shortcut_events/redo_undo_handler_test.dart
- Enable undo/redo function when the selection is null
=> fix: unable to undo/redo when the selection is null

lib/src/editor/block_component/table_block_component/table_action_menu.dart, lib/src/editor/toolbar/desktop/floating_toolbar.dart, lib/src/editor/toolbar/desktop/items/color/color_menu.dart, lib/src/editor/toolbar/desktop/items/color/color_picker.dart, test/new/toolbar/desktop/items/color/color_picker_test.dart
- enable pass custom color from outside to ColorMenu
- add toolbarBuilder for FloatingToolbar
=> chore: enable pass custom color from outside

lib/src/editor/editor_component/service/selection/desktop_selection_service.dart
https://github.com/user-attachments/assets/77d1a7a0-e26c-4092-9940-41572e57e458
https://github.com/user-attachments/assets/78b79349-668a-4928-9a37-f4eb978cda4f
=> fix: shift+click not working if beginning is out of the window

lib/src/editor/toolbar/desktop/floating_toolbar.dart
In order to distinguish the reason for recreating FloatingToolbar
=> fix: add isMetricsChanged to FloatingToolbarBuilder

.github/workflows/test.yml, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/ios/Runner/AppDelegate.swift, example/lib/home_page.dart, example/lib/main.dart, example/lib/pages/collab_editor_offline.dart, example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/pubspec.yaml, lib/src/editor/editor_component/service/scroll/auto_scrollable_widget.dart
Showcase:
https://github.com/user-attachments/assets/3a209156-da3e-4b4b-b2de-1918f40ebad0
=> Adding offline collaboration example using appflowy_editor_sync_plugin
